# 0.Setup and data loading

In [1]:
import pandas as pd
import numpy as np
import os
import random

# ignore warnings
import warnings
warnings.filterwarnings('ignore')

import importlib
import train_models_util
import feature_importance
import evaluate_models_util
importlib.reload(train_models_util)
importlib.reload(feature_importance)
importlib.reload(evaluate_models_util)
from train_models_util import (
    train_xgb_optuna, 
    train_catboost_optuna, 
    train_lgbm_optuna
)
from evaluate_models_util import evaluate_and_log
from feature_importance import get_top_features_shap

# set all random seeds for reproducibility
np.random.seed(42)
random.seed(42)
os.environ['PYTHONHASHSEED'] = str(42)

In [2]:
EXPERIMENT_NAME = "Fraud-detection-custom-thresholds_v13_downsample_auc_pr"

In [3]:
from functools import partial

common_eval_kwargs = dict(
    results_dir="ai-gen/results",
    top_k_list=[1000, 5000, 10000],
    cost_threshold_selection=True,
    bootstrap_n=200,
    time_col="TransactionDT",
    time_unit="s",
    time_freq="M",
    time_origin="start",
    min_slice_size=500,
)
evaluate_and_log = partial(evaluate_and_log, **common_eval_kwargs)

In [4]:
data_folder = 'ieee-fraud-detection-data/processed/'

data = pd.read_csv(f'{data_folder}train_processed.csv')

In [5]:
data = data.drop(columns=['TransactionDT','uid'], axis='columns')

In [6]:
cat_cols = np.array(data.select_dtypes(include=['object']).columns)
for c in cat_cols:
    if c in data.columns:
        if data[c].isnull().sum()>0:
            data[c].fillna('missing', inplace=True)
        data[c] = data[c].astype('category')

In [7]:
# attempt without suffle, since the data have time relation
n = len(data)
split_idx = int(n * 0.8) 

train = data.iloc[:split_idx]
test = data.iloc[split_idx:]

In [8]:
del data, cat_cols, c #,fraud_indices, non_fraud_indices,
import gc
gc.collect()

100

In [9]:
# split to X and y
X_train = train.drop(columns='isFraud', axis='columns')
X_test = test.drop(columns='isFraud', axis='columns')

y_train = train['isFraud']
y_test = test['isFraud']

In [10]:
from sklearn.preprocessing import OneHotEncoder

def encode_categoricals(
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    cardinality_threshold: int = 10,
    drop_first: bool = False,
    missing_sentinel: str = "__MISSING__",
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, any]]:
    """Encode categorical features in `X_train` and `X_test`.

    - Categorical columns with unique values > `cardinality_threshold` are
      frequency-encoded (mapping categories to their training frequency).
    - Other categorical columns are one-hot-encoded (trained on `X_train`,
      `handle_unknown='ignore'` to allow unseen test categories).

    Returns (X_train_encoded, X_test_encoded, encoders) where `encoders` is a
    dict containing the fitted OneHotEncoder (if any) and frequency maps.

    Args:
      X_train, X_test: pandas DataFrames with identical columns.
      cardinality_threshold: threshold above which frequency encoding is used.
      drop_first: whether to drop the first level in one-hot encoding.
      missing_sentinel: placeholder used for NaN categories when fitting.

    Example:
      X_tr_enc, X_te_enc, enc = encode_categoricals(X_train, X_test)
    """
    if not isinstance(X_train, pd.DataFrame) or not isinstance(
        X_test, pd.DataFrame
    ):
        raise TypeError("X_train and X_test must be pandas DataFrame objects")

    # Copy inputs to avoid inplace changes
    X_train = X_train.copy()
    X_test = X_test.copy()

    # Identify categorical columns (object or category dtype)
    cat_cols = list(
        X_train.select_dtypes(include=["object", "category"]).columns
    )

    # Containers for outputs
    freq_maps: dict[str, dict[any, float]] = {}
    onehot_cols = []

    # Determine which columns get frequency encoding vs one-hot
    for col in cat_cols:
        n_unique = X_train[col].nunique(dropna=False)
        if n_unique > cardinality_threshold:
            # frequency encoding
            vc = X_train[col].astype(object).fillna(missing_sentinel).value_counts(normalize=True)
            freq_map = vc.to_dict()
            freq_maps[col] = freq_map
        else:
            onehot_cols.append(col)

    # Apply frequency encoding
    for col, fmap in freq_maps.items():
        X_train[col] = X_train[col].astype(object).fillna(missing_sentinel).map(fmap).fillna(0.0)
        X_test[col] = X_test[col].astype(object).fillna(missing_sentinel).map(fmap).fillna(0.0)

    # Apply one-hot encoding on remaining categorical columns
    ohe = None
    ohe_feature_names = []
    if onehot_cols:
        # Replace NaN with sentinel to treat as a category
        X_train_ohe_input = X_train[onehot_cols].astype(object).fillna(missing_sentinel)
        X_test_ohe_input = X_test[onehot_cols].astype(object).fillna(missing_sentinel)

        ohe = OneHotEncoder(sparse_output=False, handle_unknown="ignore", drop="first" if drop_first else None)
        ohe.fit(X_train_ohe_input)

        X_train_ohe = ohe.transform(X_train_ohe_input)
        X_test_ohe = ohe.transform(X_test_ohe_input)

        ohe_feature_names = list(ohe.get_feature_names_out(onehot_cols))

        X_train_ohe_df = pd.DataFrame(
            X_train_ohe, columns=ohe_feature_names, index=X_train.index
        )
        X_test_ohe_df = pd.DataFrame(
            X_test_ohe, columns=ohe_feature_names, index=X_test.index
        )

    # Build final DataFrames: start with non-categorical columns
    non_cat_cols = [c for c in X_train.columns if c not in cat_cols]

    X_train_final = X_train[non_cat_cols].copy()
    X_test_final = X_test[non_cat_cols].copy()

    # Add frequency-encoded columns (they replaced originals in-place above)
    for col in freq_maps.keys():
        X_train_final[col] = X_train[col]
        X_test_final[col] = X_test[col]

    # Add one-hot encoded columns
    if onehot_cols:
        X_train_final = pd.concat([X_train_final, X_train_ohe_df], axis=1)
        X_test_final = pd.concat([X_test_final, X_test_ohe_df], axis=1)
        
    return X_train_final, X_test_final

In [11]:
X_train_enc, X_test_enc = encode_categoricals(X_train, X_test)
X_train_enc.fillna(-1, inplace=True)
X_test_enc.fillna(-1,inplace=True)

In [12]:
# --- Baselines Table ---
from evaluate_models_util import run_baseline_table

results_dir = "ai-gen/results"
baseline_df = run_baseline_table(
    X_train=X_train_enc,
    y_train=y_train,
    X_test=X_test_enc,
    y_test=y_test,
    results_dir=results_dir,
    top_k_list=common_eval_kwargs["top_k_list"]
)
baseline_df.head()

,model,roc_auc,pr_auc,precision,recall,f1,custom_loss,precision_at_1000,recall_at_1000,precision_at_5000,recall_at_5000,precision_at_10000,recall_at_10000,cost_opt_threshold,cost_opt_custom_loss
0,log_reg,0.796890,0.141491,0.096979,0.675443,0.169607,1.333187,0.224,0.055118,0.2156,0.265256,0.1640,0.403543,0.314891,0.846420
1,decision_tree,0.851274,0.373284,0.141678,0.743602,0.238009,1.037254,0.738,0.181594,0.3786,0.465797,0.2357,0.579970,0.129088,0.786382
2,random_forest,0.914191,0.526285,0.246530,0.738681,0.369682,0.976860,0.874,0.215059,0.4494,0.552904,0.2833,0.697096,0.284937,0.562138

In [13]:
del X_train_enc, X_test_enc

## Downsample

In [9]:
NON_FRAUD_RATIO = 5   # keep 5 non-fraud per fraud
RANDOM_STATE = 42

#Save original index
train["original_index"] = train.index

fraud_df = train[train['isFraud'] == 1]
non_fraud_df = train[train['isFraud'] == 0]

# -----------------------------
# COMPUTE SAMPLE SIZE
# -----------------------------
target_non_fraud = min(
    len(non_fraud_df),
    NON_FRAUD_RATIO * len(fraud_df)
)

# -----------------------------
# DOWNSAMPLE
# -----------------------------
downsampled_non_fraud = non_fraud_df.sample(
    n=target_non_fraud,
    random_state=RANDOM_STATE
)

train = pd.concat([fraud_df, downsampled_non_fraud], ignore_index=True)

# Restore original order
train = train.sort_values("original_index")

# Optional: drop helper column
train = train.drop(columns=["original_index"])

print("Done.")
print(f"Fraud kept: {len(fraud_df)}")
print(f"Non-fraud kept: {len(downsampled_non_fraud)}")
print(f"Final size: {len(train)}")

Done.
Fraud kept: 16599
Non-fraud kept: 82995
Final size: 99594

In [10]:
del downsampled_non_fraud, target_non_fraud, fraud_df, non_fraud_df
import gc
gc.collect()

0

## 1. Full Features

In [11]:
# split to X and y
X_train = train.drop(columns='isFraud', axis='columns')
X_test = test.drop(columns='isFraud', axis='columns')

y_train = train['isFraud']
y_test = test['isFraud']

del train, test

In [12]:
X_train.shape, X_test.shape

((99594, 748), (118108, 748))

### 1.1. XGBoost

In [18]:
model_xgboost_full, best_params_xgboost_full, hist_df, plot_paths = train_xgb_optuna(X_train, y_train)

[I 2026-01-31 13:09:55,697] A new study created in memory with name: xgboost_aucpr_optimization

[Optuna XGBoost Tuning]:   0%|          | 0/30 [00:00<?, ?trial/s]

[I 2026-01-31 13:12:50,400] Trial 0 finished with value: 0.9151365422383405 and parameters: {'learning_rate': 0.028034548908449954, 'max_depth': 8, 'subsample': 0.6350600910823879, 'colsample_bytree': 0.7516910725835851, 'min_child_weight': 0.003532135425196755, 'gamma': 4.248086544017921}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:15:02,906] Trial 1 finished with value: 0.88053131114245 and parameters: {'learning_rate': 0.015927312459942812, 'max_depth': 3, 'subsample': 0.9204096372373793, 'colsample_bytree': 0.8026186286983974, 'min_child_weight': 0.0015082117366341304, 'gamma': 3.5583605466193804}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:17:17,095] Trial 2 finished with value: 0.8918738354017939 and parameters: {'learning_rate': 0.027318647252795432, 'max_depth': 4, 'subsample': 0.9343435628110777, 'colsample_bytree': 0.8548189250368248, 'min_child_weight': 0.41213242694067964, 'gamma': 1.0185024052308633}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:20:02,841] Trial 3 finished with value: 0.9034157749916041 and parameters: {'learning_rate': 0.01582548860787978, 'max_depth': 6, 'subsample': 0.996795293807176, 'colsample_bytree': 0.8004770092240068, 'min_child_weight': 0.06291652886569478, 'gamma': 4.233120069286901}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:22:56,894] Trial 4 finished with value: 0.9148147501917627 and parameters: {'learning_rate': 0.017040350163935257, 'max_depth': 8, 'subsample': 0.5548641339244484, 'colsample_bytree': 0.6100531109834079, 'min_child_weight': 0.0586903598455584, 'gamma': 4.716927664717518}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:25:24,632] Trial 5 finished with value: 0.8981099195915235 and parameters: {'learning_rate': 0.015687526535399458, 'max_depth': 5, 'subsample': 0.6979987410131723, 'colsample_bytree': 0.7128678073349792, 'min_child_weight': 0.009285009015415418, 'gamma': 0.19068215065468408}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:27:38,116] Trial 6 finished with value: 0.8963979444238784 and parameters: {'learning_rate': 0.014900223721406852, 'max_depth': 5, 'subsample': 0.6254309855267606, 'colsample_bytree': 0.751253973200405, 'min_child_weight': 0.029362500909480976, 'gamma': 3.9123992125974603}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:29:53,310] Trial 7 finished with value: 0.8884846580585695 and parameters: {'learning_rate': 0.013264095199759022, 'max_depth': 4, 'subsample': 0.7741440448670114, 'colsample_bytree': 0.5767916650398246, 'min_child_weight': 0.003691613109684095, 'gamma': 4.433750208819708}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:32:37,105] Trial 8 finished with value: 0.8997367862914333 and parameters: {'learning_rate': 0.011457039968443796, 'max_depth': 6, 'subsample': 0.5584478829095499, 'colsample_bytree': 0.9390795997891543, 'min_child_weight': 0.0054483672044370905, 'gamma': 2.9516661392512527}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:34:40,618] Trial 9 finished with value: 0.8840476690031401 and parameters: {'learning_rate': 0.0260977945171676, 'max_depth': 3, 'subsample': 0.5740212950221013, 'colsample_bytree': 0.8858520249397428, 'min_child_weight': 0.10381649571031877, 'gamma': 2.9447022229643034}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:38:12,960] Trial 10 finished with value: 0.9148108144006567 and parameters: {'learning_rate': 0.022984436873470775, 'max_depth': 8, 'subsample': 0.7555773296192496, 'colsample_bytree': 0.9924145797829547, 'min_child_weight': 0.0011959370783737136, 'gamma': 1.838708133200864}. Best is trial 0 with value: 0.9151365422383405.
[I 2026-01-31 13:41:00,512] Trial 11 finished with value: 0.916055048234038 and parameters: {'learning_rate': 0.020386437100278564, 'max_depth': 8, 'subsample': 0.5073827964307454, 'colsample_bytree': 0.5888889899803559, 'min_child_weight': 0.02289976501135721, 'gamma': 4.8827527282812}. Best is trial 11 with value: 0.916055048234038.
[I 2026-01-31 13:43:34,078] Trial 12 finished with value: 0.9112169777964082 and parameters: {'learning_rate': 0.021709584809499798, 'max_depth': 7, 'subsample': 0.5058112998962381, 'colsample_bytree': 0.6603258709935571, 'min_child_weight': 0.014098689855291181, 'gamma': 4.803416432963195}. Best is trial 11 with value: 0.916055048234038.
[I 2026-01-31 13:46:05,365] Trial 13 finished with value: 0.9061483487596274 and parameters: {'learning_rate': 0.02968201108058544, 'max_depth': 7, 'subsample': 0.663354754639012, 'colsample_bytree': 0.516448221088328, 'min_child_weight': 0.37553415692969294, 'gamma': 4.983870822331258}. Best is trial 11 with value: 0.916055048234038.
[I 2026-01-31 13:48:53,334] Trial 14 finished with value: 0.9141683948542334 and parameters: {'learning_rate': 0.019422173042471493, 'max_depth': 8, 'subsample': 0.5096414278902024, 'colsample_bytree': 0.687917785761976, 'min_child_weight': 0.020724460572089234, 'gamma': 3.373256007243032}. Best is trial 11 with value: 0.916055048234038.
[I 2026-01-31 13:51:25,862] Trial 15 finished with value: 0.9149590283775453 and parameters: {'learning_rate': 0.02501767341608899, 'max_depth': 7, 'subsample': 0.8264748674273119, 'colsample_bytree': 0.6150935266728965, 'min_child_weight': 0.0038309572865630613, 'gamma': 2.3800676877510165}. Best is trial 11 with value: 0.916055048234038.
[I 2026-01-31 13:53:43,725] Trial 16 finished with value: 0.9124918056289862 and parameters: {'learning_rate': 0.029795327468200968, 'max_depth': 7, 'subsample': 0.6262826933226092, 'colsample_bytree': 0.5055655114767421, 'min_child_weight': 0.12381317314927022, 'gamma': 3.9591978372434165}. Best is trial 11 with value: 0.916055048234038.
[I 2026-01-31 13:56:40,609] Trial 17 finished with value: 0.9148625336708656 and parameters: {'learning_rate': 0.019990197909129093, 'max_depth': 8, 'subsample': 0.700928817346209, 'colsample_bytree': 0.7462685659657704, 'min_child_weight': 0.002270247208321773, 'gamma': 1.9803615897885765}. Best is trial 11 with value: 0.916055048234038.
[I 2026-01-31 13:58:56,022] Trial 18 finished with value: 0.9083072865595513 and parameters: {'learning_rate': 0.023387613548574167, 'max_depth': 6, 'subsample': 0.6067709211142253, 'colsample_bytree': 0.6508911400808906, 'min_child_weight': 0.0074122030029212145, 'gamma': 3.6466599166523865}. Best is trial 11 with value: 0.916055048234038.
[I 2026-01-31 14:01:46,592] Trial 19 finished with value: 0.9176954365053959 and parameters: {'learning_rate': 0.018371257650656784, 'max_depth': 8, 'subsample': 0.8258787349558746, 'colsample_bytree': 0.5705839616020891, 'min_child_weight': 0.013763200807720198, 'gamma': 4.324884455105092}. Best is trial 19 with value: 0.9176954365053959.
[I 2026-01-31 14:03:56,425] Trial 20 finished with value: 0.9006189402846004 and parameters: {'learning_rate': 0.018641967740865437, 'max_depth': 7, 'subsample': 0.8391157637855395, 'colsample_bytree': 0.5509971225843409, 'min_child_weight': 0.7948958099689573, 'gamma': 3.184466726224078}. Best is trial 19 with value: 0.9176954365053959.
[I 2026-01-31 14:06:53,521] Trial 21 finished with value: 0.9169554012473636 and parameters: {'learning_rate': 0.017900098091817487, 'max_depth': 8, 'subsample': 0.8224383787479057, 'colsample_bytree': 0.5763884442836891, 'min_child_weight': 0.014052661920428968, 'gamma': 4.344988602524909}. Best is trial 19 with value: 0.9176954365053959.
[I 2026-01-31 14:09:53,064] Trial 22 finished with value: 0.9171905310921056 and parameters: {'learning_rate': 0.017743900678378027, 'max_depth': 8, 'subsample': 0.8146325002972472, 'colsample_bytree': 0.5700878397265454, 'min_child_weight': 0.014005865290758838, 'gamma': 4.716246445319922}. Best is trial 19 with value: 0.9176954365053959.
[I 2026-01-31 14:12:34,898] Trial 23 finished with value: 0.9132219823114619 and parameters: {'learning_rate': 0.017998278737835025, 'max_depth': 7, 'subsample': 0.8249569186831708, 'colsample_bytree': 0.543417109844371, 'min_child_weight': 0.012922649342828635, 'gamma': 4.218288450016286}. Best is trial 19 with value: 0.9176954365053959.
[I 2026-01-31 14:15:43,336] Trial 24 finished with value: 0.9143766798304552 and parameters: {'learning_rate': 0.013606578635238356, 'max_depth': 8, 'subsample': 0.8791826630728018, 'colsample_bytree': 0.6426450411939509, 'min_child_weight': 0.03426332127026566, 'gamma': 4.54863052382046}. Best is trial 19 with value: 0.9176954365053959.
[I 2026-01-31 14:18:36,701] Trial 25 finished with value: 0.9180062047813443 and parameters: {'learning_rate': 0.021350305561301568, 'max_depth': 8, 'subsample': 0.7849984398241621, 'colsample_bytree': 0.554252404775153, 'min_child_weight': 0.012152117791512807, 'gamma': 3.9239906293821343}. Best is trial 25 with value: 0.9180062047813443.
[I 2026-01-31 14:21:10,254] Trial 26 finished with value: 0.9143087898023111 and parameters: {'learning_rate': 0.021738263470368894, 'max_depth': 7, 'subsample': 0.7858407748675136, 'colsample_bytree': 0.5002823851602659, 'min_child_weight': 0.03937794461208926, 'gamma': 3.8815326925769087}. Best is trial 25 with value: 0.9180062047813443.
[I 2026-01-31 14:23:28,022] Trial 27 finished with value: 0.9083907329686506 and parameters: {'learning_rate': 0.02075212945831937, 'max_depth': 6, 'subsample': 0.7191925993738918, 'colsample_bytree': 0.5489462615312637, 'min_child_weight': 0.0072595015508207265, 'gamma': 2.672108523084121}. Best is trial 25 with value: 0.9180062047813443.
[I 2026-01-31 14:26:19,697] Trial 28 finished with value: 0.916989215927081 and parameters: {'learning_rate': 0.024100054145545807, 'max_depth': 8, 'subsample': 0.9070835951296893, 'colsample_bytree': 0.6158969103065237, 'min_child_weight': 0.01793398299298862, 'gamma': 3.702433979534041}. Best is trial 25 with value: 0.9180062047813443.
[I 2026-01-31 14:29:09,329] Trial 29 finished with value: 0.915839563009181 and parameters: {'learning_rate': 0.02232702223233642, 'max_depth': 8, 'subsample': 0.8726744065371902, 'colsample_bytree': 0.7039546686456045, 'min_child_weight': 0.005433522296576308, 'gamma': 4.506982677624738}. Best is trial 25 with value: 0.9180062047813443.

[INFO] Best XGBoost params: {'learning_rate': 0.021350305561301568, 'max_depth': 8, 'subsample': 0.7849984398241621, 'colsample_bytree': 0.554252404775153, 'min_child_weight': 0.012152117791512807, 'gamma': 3.9239906293821343}
[0]	validation_0-auc:0.82230
[100]	validation_0-auc:0.92133
[200]	validation_0-auc:0.93197
[300]	validation_0-auc:0.93660
[400]	validation_0-auc:0.93953
[500]	validation_0-auc:0.94020
[600]	validation_0-auc:0.94080
[700]	validation_0-auc:0.94107
[800]	validation_0-auc:0.94124
[890]	validation_0-auc:0.94118

In [19]:
evaluate_and_log(model_xgboost_full, X_test, y_test, experiment_name=EXPERIMENT_NAME, run_name="XGBoost_Optuna_fullfeatures", hp_search_history=hist_df, hp_search_plots= plot_paths)

2026/01/31 14:31:59 INFO mlflow.tracking.fluent: Experiment with name 'Fraud-detection-custom-thresholds_v12_downsample_auc_pr' does not exist. Creating a new experiment.

[INFO] Logged metrics: {'roc_auc': np.float64(0.9069201345774955), 'pr_auc': np.float64(0.5192150427811373), 'precision': 0.29597946963216426, 'recall': 0.6811023622047244, 'f1': 0.41264162194394755, 'custom_loss': np.float64(1.1530463643444984), 'precision_at_1000': 0.874, 'recall_at_1000': 0.21505905511811024, 'precision_at_5000': 0.445, 'recall_at_5000': 0.5474901574803149, 'precision_at_10000': 0.2819, 'recall_at_10000': 0.6936515748031497, 'cost_opt_threshold': 0.09427642661273179, 'cost_opt_custom_loss': 0.6077911741795645, 'cost_opt_precision': 0.07881599201231435, 'cost_opt_recall': 0.9323326771653543, 'cost_opt_f1': 0.14534504583988644}
[INFO] Logged SHAP summary plot.

2026/01/31 14:32:23 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.

{'roc_auc': np.float64(0.9069201345774955),
 'pr_auc': np.float64(0.5192150427811373),
 'precision': 0.29597946963216426,
 'recall': 0.6811023622047244,
 'f1': 0.41264162194394755,
 'custom_loss': np.float64(1.1530463643444984),
 'precision_at_1000': 0.874,
 'recall_at_1000': 0.21505905511811024,
 'precision_at_5000': 0.445,
 'recall_at_5000': 0.5474901574803149,
 'precision_at_10000': 0.2819,
 'recall_at_10000': 0.6936515748031497,
 'cost_opt_threshold': 0.09427642661273179,
 'cost_opt_custom_loss': 0.6077911741795645,
 'cost_opt_precision': 0.07881599201231435,
 'cost_opt_recall': 0.9323326771653543,
 'cost_opt_f1': 0.14534504583988644}

### 1.2. LightGBM

In [20]:
model_lgbm_full, best_params_lgbm_full, hist_df, plot_paths = train_lgbm_optuna(X_train, y_train)

[I 2026-01-31 14:32:34,068] A new study created in memory with name: lgbm_aucpr_optimization

[Optuna LightGBM Tuning]:   0%|          | 0/30 [00:00<?, ?trial/s]

[I 2026-01-31 14:34:41,543] Trial 0 finished with value: 0.9264325394834684 and parameters: {'num_leaves': 227, 'max_depth': 13, 'learning_rate': 0.01365378241459215, 'min_child_samples': 27, 'reg_alpha': 0.3278882177800078, 'reg_lambda': 0.06230800029395145, 'colsample_bytree': 0.8570103246134058, 'subsample': 0.9819620313235848}. Best is trial 0 with value: 0.9264325394834684.
[I 2026-01-31 14:36:16,503] Trial 1 finished with value: 0.9292543850969076 and parameters: {'num_leaves': 325, 'max_depth': 15, 'learning_rate': 0.02874768569590319, 'min_child_samples': 53, 'reg_alpha': 0.10243401105177619, 'reg_lambda': 0.02282647894307893, 'colsample_bytree': 0.8272843652151214, 'subsample': 0.9857925579523783}. Best is trial 1 with value: 0.9292543850969076.
[I 2026-01-31 14:38:51,553] Trial 2 finished with value: 0.9271709628611292 and parameters: {'num_leaves': 388, 'max_depth': 14, 'learning_rate': 0.013152757488814093, 'min_child_samples': 18, 'reg_alpha': 0.4899658079974681, 'reg_lambda': 0.19599619349635256, 'colsample_bytree': 0.8375036017962416, 'subsample': 0.8955964471361378}. Best is trial 1 with value: 0.9292543850969076.
[I 2026-01-31 14:40:25,507] Trial 3 finished with value: 0.927367228329135 and parameters: {'num_leaves': 133, 'max_depth': 15, 'learning_rate': 0.025657786217185265, 'min_child_samples': 18, 'reg_alpha': 0.42740871927972435, 'reg_lambda': 0.27349548361534903, 'colsample_bytree': 0.8806389014834796, 'subsample': 0.8518213641030208}. Best is trial 1 with value: 0.9292543850969076.
[I 2026-01-31 14:42:30,210] Trial 4 finished with value: 0.9289869840201744 and parameters: {'num_leaves': 258, 'max_depth': 16, 'learning_rate': 0.016841195338095107, 'min_child_samples': 82, 'reg_alpha': 0.10110496230219795, 'reg_lambda': 0.435141648071009, 'colsample_bytree': 0.9996209834267081, 'subsample': 0.8974476227511092}. Best is trial 1 with value: 0.9292543850969076.
[I 2026-01-31 14:44:46,591] Trial 5 finished with value: 0.9318336612243234 and parameters: {'num_leaves': 438, 'max_depth': 19, 'learning_rate': 0.023407390158312613, 'min_child_samples': 65, 'reg_alpha': 0.37315343065504375, 'reg_lambda': 0.19934281052450814, 'colsample_bytree': 0.9047536732625032, 'subsample': 0.990756043308619}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 14:46:33,328] Trial 6 finished with value: 0.9278027799084922 and parameters: {'num_leaves': 309, 'max_depth': 14, 'learning_rate': 0.022602326636956792, 'min_child_samples': 32, 'reg_alpha': 0.3191435823491176, 'reg_lambda': 0.4763235152180989, 'colsample_bytree': 0.8477704872982179, 'subsample': 0.9367772401959154}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 14:48:02,732] Trial 7 finished with value: 0.9294478362364309 and parameters: {'num_leaves': 493, 'max_depth': 13, 'learning_rate': 0.02487565391941509, 'min_child_samples': 91, 'reg_alpha': 0.08947492116010253, 'reg_lambda': 0.3554995724368265, 'colsample_bytree': 0.8592197918780252, 'subsample': 0.8496923283241253}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 14:50:01,844] Trial 8 finished with value: 0.9262345982184549 and parameters: {'num_leaves': 200, 'max_depth': 13, 'learning_rate': 0.01179395981830713, 'min_child_samples': 40, 'reg_alpha': 0.4417878325520248, 'reg_lambda': 0.4397910644347564, 'colsample_bytree': 0.9055233445616431, 'subsample': 0.9862962587178937}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 14:51:48,547] Trial 9 finished with value: 0.9241398279212101 and parameters: {'num_leaves': 170, 'max_depth': 13, 'learning_rate': 0.019740727574717218, 'min_child_samples': 11, 'reg_alpha': 0.224136152401397, 'reg_lambda': 0.30199275749855015, 'colsample_bytree': 0.9610179496151143, 'subsample': 0.830718558520097}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 14:54:06,001] Trial 10 finished with value: 0.9318121838229848 and parameters: {'num_leaves': 510, 'max_depth': 20, 'learning_rate': 0.029930466176678383, 'min_child_samples': 69, 'reg_alpha': 0.2531949490992511, 'reg_lambda': 0.15783235577885762, 'colsample_bytree': 0.9255152054973391, 'subsample': 0.9317898902149832}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 14:55:51,388] Trial 11 finished with value: 0.9310325878300371 and parameters: {'num_leaves': 511, 'max_depth': 20, 'learning_rate': 0.02978848593898771, 'min_child_samples': 72, 'reg_alpha': 0.20470007174348476, 'reg_lambda': 0.16154071012573398, 'colsample_bytree': 0.9236543722181285, 'subsample': 0.940585140635652}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 14:58:07,440] Trial 12 finished with value: 0.9310802050731537 and parameters: {'num_leaves': 439, 'max_depth': 20, 'learning_rate': 0.02581248026056472, 'min_child_samples': 64, 'reg_alpha': 0.31872284158116815, 'reg_lambda': 0.1357355598205477, 'colsample_bytree': 0.9361646364808888, 'subsample': 0.9430756130187709}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 15:00:32,401] Trial 13 finished with value: 0.9287123405622717 and parameters: {'num_leaves': 446, 'max_depth': 18, 'learning_rate': 0.020657365796422574, 'min_child_samples': 52, 'reg_alpha': 0.3849812072844634, 'reg_lambda': 0.10296531292598682, 'colsample_bytree': 0.955885508431334, 'subsample': 0.9468257000132065}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 15:01:43,050] Trial 14 finished with value: 0.9268992126598317 and parameters: {'num_leaves': 417, 'max_depth': 10, 'learning_rate': 0.027668818815230457, 'min_child_samples': 70, 'reg_alpha': 0.1873031679502632, 'reg_lambda': 0.22033000520869234, 'colsample_bytree': 0.8942593891358473, 'subsample': 0.9124500630018451}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 15:03:43,752] Trial 15 finished with value: 0.9303927426485501 and parameters: {'num_leaves': 360, 'max_depth': 18, 'learning_rate': 0.02243927628716547, 'min_child_samples': 96, 'reg_alpha': 0.2646478254765271, 'reg_lambda': 0.3143405380915334, 'colsample_bytree': 0.9217141103069327, 'subsample': 0.8752147495203544}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 15:05:48,672] Trial 16 finished with value: 0.9317863156094992 and parameters: {'num_leaves': 473, 'max_depth': 18, 'learning_rate': 0.018477149031286114, 'min_child_samples': 81, 'reg_alpha': 0.16767296777716764, 'reg_lambda': 0.23514081222918964, 'colsample_bytree': 0.8005779597460277, 'subsample': 0.9612336443143411}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 15:08:25,738] Trial 17 finished with value: 0.9302146812927253 and parameters: {'num_leaves': 396, 'max_depth': 19, 'learning_rate': 0.01607762233561396, 'min_child_samples': 63, 'reg_alpha': 0.018465115616823263, 'reg_lambda': 0.09717396868151887, 'colsample_bytree': 0.956717349693638, 'subsample': 0.915632892736638}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 15:10:27,809] Trial 18 finished with value: 0.9281475268248651 and parameters: {'num_leaves': 470, 'max_depth': 17, 'learning_rate': 0.023170303567891518, 'min_child_samples': 49, 'reg_alpha': 0.3788766981636972, 'reg_lambda': 0.17482825830873885, 'colsample_bytree': 0.9892088496783739, 'subsample': 0.9659009709475248}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 15:12:12,292] Trial 19 finished with value: 0.9316860851256763 and parameters: {'num_leaves': 363, 'max_depth': 20, 'learning_rate': 0.02729575930690376, 'min_child_samples': 82, 'reg_alpha': 0.28988026471239836, 'reg_lambda': 0.3581470085530697, 'colsample_bytree': 0.8803028146558471, 'subsample': 0.8081130049786858}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 15:14:16,338] Trial 20 finished with value: 0.9296656370448314 and parameters: {'num_leaves': 443, 'max_depth': 19, 'learning_rate': 0.024085330291234754, 'min_child_samples': 44, 'reg_alpha': 0.37632933729083967, 'reg_lambda': 0.0004266958605790572, 'colsample_bytree': 0.9018761886912375, 'subsample': 0.9978784923146641}. Best is trial 5 with value: 0.9318336612243234.
[I 2026-01-31 15:16:26,624] Trial 21 finished with value: 0.9321498205902397 and parameters: {'num_leaves': 482, 'max_depth': 18, 'learning_rate': 0.018488710365808198, 'min_child_samples': 80, 'reg_alpha': 0.1617316012284523, 'reg_lambda': 0.22633637426525133, 'colsample_bytree': 0.8113788390193121, 'subsample': 0.9679582081478849}. Best is trial 21 with value: 0.9321498205902397.
[I 2026-01-31 15:18:30,030] Trial 22 finished with value: 0.9318259409111677 and parameters: {'num_leaves': 502, 'max_depth': 17, 'learning_rate': 0.02082316393154998, 'min_child_samples': 60, 'reg_alpha': 0.14575836282305019, 'reg_lambda': 0.2626861549114788, 'colsample_bytree': 0.8135244243998756, 'subsample': 0.9703022438624684}. Best is trial 21 with value: 0.9321498205902397.
[I 2026-01-31 15:20:44,888] Trial 23 finished with value: 0.9312356487894355 and parameters: {'num_leaves': 471, 'max_depth': 17, 'learning_rate': 0.01997930293317582, 'min_child_samples': 60, 'reg_alpha': 0.13844669147047028, 'reg_lambda': 0.26053237827475717, 'colsample_bytree': 0.8089951953960375, 'subsample': 0.9660250641319024}. Best is trial 21 with value: 0.9321498205902397.
[I 2026-01-31 15:22:47,479] Trial 24 finished with value: 0.9309888463864096 and parameters: {'num_leaves': 422, 'max_depth': 17, 'learning_rate': 0.017530175412508175, 'min_child_samples': 88, 'reg_alpha': 0.14746300989836392, 'reg_lambda': 0.337809854849794, 'colsample_bytree': 0.8223489929859112, 'subsample': 0.9983784833228291}. Best is trial 21 with value: 0.9321498205902397.
[I 2026-01-31 15:24:37,355] Trial 25 finished with value: 0.9310415965786136 and parameters: {'num_leaves': 478, 'max_depth': 16, 'learning_rate': 0.02123505041050999, 'min_child_samples': 75, 'reg_alpha': 0.03414054661376864, 'reg_lambda': 0.21002436072062552, 'colsample_bytree': 0.8185993400526151, 'subsample': 0.9710213615833755}. Best is trial 21 with value: 0.9321498205902397.
[I 2026-01-31 15:26:43,740] Trial 26 finished with value: 0.9313617309022396 and parameters: {'num_leaves': 398, 'max_depth': 19, 'learning_rate': 0.01863408016494842, 'min_child_samples': 100, 'reg_alpha': 0.05508970775150537, 'reg_lambda': 0.26575288182768486, 'colsample_bytree': 0.8395614212821083, 'subsample': 0.9597103910541431}. Best is trial 21 with value: 0.9321498205902397.
[I 2026-01-31 15:29:01,131] Trial 27 finished with value: 0.930252366213589 and parameters: {'num_leaves': 452, 'max_depth': 16, 'learning_rate': 0.014974567772974956, 'min_child_samples': 59, 'reg_alpha': 0.22724678188902797, 'reg_lambda': 0.39490174178300214, 'colsample_bytree': 0.8637764697098866, 'subsample': 0.92105854010626}. Best is trial 21 with value: 0.9321498205902397.
[I 2026-01-31 15:31:32,100] Trial 28 finished with value: 0.9315420050120459 and parameters: {'num_leaves': 297, 'max_depth': 18, 'learning_rate': 0.010366028422720384, 'min_child_samples': 75, 'reg_alpha': 0.1573672785169871, 'reg_lambda': 0.12319397686674322, 'colsample_bytree': 0.8706692206592408, 'subsample': 0.9769918445669887}. Best is trial 21 with value: 0.9321498205902397.
[I 2026-01-31 15:32:54,012] Trial 29 finished with value: 0.9253200153622422 and parameters: {'num_leaves': 367, 'max_depth': 10, 'learning_rate': 0.021598708050080722, 'min_child_samples': 41, 'reg_alpha': 0.12293341678926084, 'reg_lambda': 0.060573185131531176, 'colsample_bytree': 0.8503059922025759, 'subsample': 0.9544511569022586}. Best is trial 21 with value: 0.9321498205902397.

[INFO] Best LightGBM params: {'num_leaves': 482, 'max_depth': 18, 'learning_rate': 0.018488710365808198, 'min_child_samples': 80, 'reg_alpha': 0.1617316012284523, 'reg_lambda': 0.22633637426525133, 'colsample_bytree': 0.8113788390193121, 'subsample': 0.9679582081478849}
[50]	valid_0's auc: 0.938058	valid_0's binary_logloss: 0.297923
[100]	valid_0's auc: 0.944604	valid_0's binary_logloss: 0.252791
[150]	valid_0's auc: 0.948164	valid_0's binary_logloss: 0.230456
[200]	valid_0's auc: 0.94989	valid_0's binary_logloss: 0.218719
[250]	valid_0's auc: 0.95034	valid_0's binary_logloss: 0.210981
[300]	valid_0's auc: 0.950529	valid_0's binary_logloss: 0.205859
[350]	valid_0's auc: 0.950784	valid_0's binary_logloss: 0.201628
[400]	valid_0's auc: 0.951069	valid_0's binary_logloss: 0.197815
[450]	valid_0's auc: 0.951225	valid_0's binary_logloss: 0.194951
[500]	valid_0's auc: 0.951169	valid_0's binary_logloss: 0.193299
[550]	valid_0's auc: 0.95118	valid_0's binary_logloss: 0.19244
[600]	valid_0's auc: 0.95103	valid_0's binary_logloss: 0.192338

In [21]:
evaluate_and_log(model_lgbm_full,  X_test, y_test, experiment_name=EXPERIMENT_NAME, run_name="LightGBM_Optuna_fullfeatures", hp_search_history=hist_df, hp_search_plots= plot_paths)

[INFO] Logged metrics: {'roc_auc': np.float64(0.9192867428637158), 'pr_auc': np.float64(0.5773310707126735), 'precision': 0.3918939055282372, 'recall': 0.6471456692913385, 'f1': 0.48816705336426913, 'custom_loss': np.float64(1.2486961086463237), 'precision_at_1000': 0.911, 'recall_at_1000': 0.22416338582677164, 'precision_at_5000': 0.4756, 'recall_at_5000': 0.5851377952755905, 'precision_at_10000': 0.2937, 'recall_at_10000': 0.7226870078740157, 'cost_opt_threshold': 0.05052316408742329, 'cost_opt_custom_loss': 0.5469654892132625, 'cost_opt_precision': 0.0869535519125683, 'cost_opt_recall': 0.9397145669291339, 'cost_opt_f1': 0.1591780593531177}
[INFO] Logged SHAP summary plot.

2026/01/31 15:35:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.

{'roc_auc': np.float64(0.9192867428637158),
 'pr_auc': np.float64(0.5773310707126735),
 'precision': 0.3918939055282372,
 'recall': 0.6471456692913385,
 'f1': 0.48816705336426913,
 'custom_loss': np.float64(1.2486961086463237),
 'precision_at_1000': 0.911,
 'recall_at_1000': 0.22416338582677164,
 'precision_at_5000': 0.4756,
 'recall_at_5000': 0.5851377952755905,
 'precision_at_10000': 0.2937,
 'recall_at_10000': 0.7226870078740157,
 'cost_opt_threshold': 0.05052316408742329,
 'cost_opt_custom_loss': 0.5469654892132625,
 'cost_opt_precision': 0.0869535519125683,
 'cost_opt_recall': 0.9397145669291339,
 'cost_opt_f1': 0.1591780593531177}

### 1.3. CatBoost

In [22]:
model_catboost_full, best_params_catboost_full, hist_df, plot_paths = train_catboost_optuna(X_train, y_train)

[I 2026-01-31 15:35:45,848] A new study created in memory with name: catboost_aucpr_optimization

[Optuna CatBoost Tuning]:   0%|          | 0/30 [00:00<?, ?trial/s]

[I 2026-01-31 15:42:22,846] Trial 0 finished with value: 0.9036874815358577 and parameters: {'learning_rate': 0.014382154792341556, 'depth': 8, 'l2_leaf_reg': 2.3463807054790107, 'subsample': 0.9171429865416272, 'border_count': 71}. Best is trial 0 with value: 0.9036874815358577.
[I 2026-01-31 15:44:58,959] Trial 1 finished with value: 0.8874070673783047 and parameters: {'learning_rate': 0.02212766438927522, 'depth': 4, 'l2_leaf_reg': 7.48674975426973, 'subsample': 0.7870527069601746, 'border_count': 77}. Best is trial 0 with value: 0.9036874815358577.
[I 2026-01-31 15:49:59,918] Trial 2 finished with value: 0.9041599811236449 and parameters: {'learning_rate': 0.021021123112037722, 'depth': 7, 'l2_leaf_reg': 9.336882148580303, 'subsample': 0.9134807694014666, 'border_count': 34}. Best is trial 2 with value: 0.9041599811236449.
[I 2026-01-31 15:57:06,941] Trial 3 finished with value: 0.9005996294802259 and parameters: {'learning_rate': 0.012174588386249581, 'depth': 8, 'l2_leaf_reg': 6.99156363892509, 'subsample': 0.9562182545968914, 'border_count': 118}. Best is trial 2 with value: 0.9041599811236449.
[I 2026-01-31 16:01:56,610] Trial 4 finished with value: 0.9042144519417441 and parameters: {'learning_rate': 0.023245549291392324, 'depth': 7, 'l2_leaf_reg': 6.908463739413451, 'subsample': 0.7576582012576972, 'border_count': 56}. Best is trial 4 with value: 0.9042144519417441.
[I 2026-01-31 16:04:23,717] Trial 5 finished with value: 0.8729121505389562 and parameters: {'learning_rate': 0.010039132711859085, 'depth': 4, 'l2_leaf_reg': 7.352213693603542, 'subsample': 0.6250084998092001, 'border_count': 60}. Best is trial 4 with value: 0.9042144519417441.
[I 2026-01-31 16:08:23,524] Trial 6 finished with value: 0.8950727267434173 and parameters: {'learning_rate': 0.01761897196438232, 'depth': 6, 'l2_leaf_reg': 1.0091087810630843, 'subsample': 0.6358717733681054, 'border_count': 101}. Best is trial 4 with value: 0.9042144519417441.
[I 2026-01-31 16:13:07,684] Trial 7 finished with value: 0.9008543938298574 and parameters: {'learning_rate': 0.019036209804049714, 'depth': 7, 'l2_leaf_reg': 5.930032983721135, 'subsample': 0.7280427954364984, 'border_count': 43}. Best is trial 4 with value: 0.9042144519417441.
[I 2026-01-31 16:19:28,270] Trial 8 finished with value: 0.9099754789486334 and parameters: {'learning_rate': 0.022181695929982686, 'depth': 8, 'l2_leaf_reg': 6.323999506314658, 'subsample': 0.832542551364339, 'border_count': 68}. Best is trial 8 with value: 0.9099754789486334.
[I 2026-01-31 16:25:56,558] Trial 9 finished with value: 0.909624122908378 and parameters: {'learning_rate': 0.0213548719126858, 'depth': 8, 'l2_leaf_reg': 5.134270729836873, 'subsample': 0.9818176883572358, 'border_count': 56}. Best is trial 8 with value: 0.9099754789486334.
[I 2026-01-31 16:27:58,851] Trial 10 finished with value: 0.8841077370728941 and parameters: {'learning_rate': 0.027845682603082338, 'depth': 3, 'l2_leaf_reg': 4.085999978282418, 'subsample': 0.8717713224128109, 'border_count': 95}. Best is trial 8 with value: 0.9099754789486334.
[I 2026-01-31 16:34:24,596] Trial 11 finished with value: 0.9123389021730551 and parameters: {'learning_rate': 0.026120917016110613, 'depth': 8, 'l2_leaf_reg': 4.356003324351562, 'subsample': 0.9937623059210065, 'border_count': 53}. Best is trial 11 with value: 0.9123389021730551.
[I 2026-01-31 16:38:39,749] Trial 12 finished with value: 0.9024742106134607 and parameters: {'learning_rate': 0.027193028885803106, 'depth': 6, 'l2_leaf_reg': 4.028780653306502, 'subsample': 0.8540061688622077, 'border_count': 87}. Best is trial 11 with value: 0.9123389021730551.
[I 2026-01-31 16:42:00,764] Trial 13 finished with value: 0.8953916514585817 and parameters: {'learning_rate': 0.025840291557763136, 'depth': 5, 'l2_leaf_reg': 3.654194674912056, 'subsample': 0.8327914096456979, 'border_count': 68}. Best is trial 11 with value: 0.9123389021730551.
[I 2026-01-31 16:47:55,275] Trial 14 finished with value: 0.9094723120993656 and parameters: {'learning_rate': 0.02510998938463334, 'depth': 8, 'l2_leaf_reg': 9.063532359674415, 'subsample': 0.7172192521758114, 'border_count': 48}. Best is trial 11 with value: 0.9123389021730551.
[I 2026-01-31 16:52:34,115] Trial 15 finished with value: 0.9082061629331216 and parameters: {'learning_rate': 0.02950031709683311, 'depth': 7, 'l2_leaf_reg': 5.591481056941862, 'subsample': 0.6883081991146737, 'border_count': 33}. Best is trial 11 with value: 0.9123389021730551.
[I 2026-01-31 16:56:59,739] Trial 16 finished with value: 0.8962618556784161 and parameters: {'learning_rate': 0.016678379169271024, 'depth': 6, 'l2_leaf_reg': 2.44542462703924, 'subsample': 0.9950937832169092, 'border_count': 83}. Best is trial 11 with value: 0.9123389021730551.
[I 2026-01-31 17:00:23,380] Trial 17 finished with value: 0.8947661813648481 and parameters: {'learning_rate': 0.023575510763863567, 'depth': 5, 'l2_leaf_reg': 4.8436258549040865, 'subsample': 0.9117632098161939, 'border_count': 65}. Best is trial 11 with value: 0.9123389021730551.
[I 2026-01-31 17:06:23,216] Trial 18 finished with value: 0.9131764436954789 and parameters: {'learning_rate': 0.029568922427186582, 'depth': 8, 'l2_leaf_reg': 8.039661981978695, 'subsample': 0.8191020186220036, 'border_count': 45}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 17:11:15,640] Trial 19 finished with value: 0.9088772405959823 and parameters: {'learning_rate': 0.02999172681908592, 'depth': 7, 'l2_leaf_reg': 8.444218621260738, 'subsample': 0.7918540818317581, 'border_count': 46}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 17:17:48,746] Trial 20 finished with value: 0.9116176336162679 and parameters: {'learning_rate': 0.027517925769202627, 'depth': 8, 'l2_leaf_reg': 8.280360381747332, 'subsample': 0.6712987722319446, 'border_count': 123}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 17:24:20,960] Trial 21 finished with value: 0.911928237165732 and parameters: {'learning_rate': 0.027875458555576625, 'depth': 8, 'l2_leaf_reg': 9.991849283164886, 'subsample': 0.6643374931941398, 'border_count': 119}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 17:29:30,243] Trial 22 finished with value: 0.905699954536213 and parameters: {'learning_rate': 0.02513277197065393, 'depth': 7, 'l2_leaf_reg': 9.526193292787616, 'subsample': 0.753207111513287, 'border_count': 112}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 17:35:46,823] Trial 23 finished with value: 0.911106130427236 and parameters: {'learning_rate': 0.02865381047307291, 'depth': 8, 'l2_leaf_reg': 9.770776362577118, 'subsample': 0.6058166082039723, 'border_count': 104}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 17:42:14,973] Trial 24 finished with value: 0.9101077727492274 and parameters: {'learning_rate': 0.026453193138670273, 'depth': 8, 'l2_leaf_reg': 8.32394377043573, 'subsample': 0.662190239602999, 'border_count': 128}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 17:47:22,794] Trial 25 finished with value: 0.9063397416117214 and parameters: {'learning_rate': 0.024161697257842084, 'depth': 7, 'l2_leaf_reg': 9.951685707995553, 'subsample': 0.9521950363683157, 'border_count': 41}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 17:51:29,823] Trial 26 finished with value: 0.9032159796631273 and parameters: {'learning_rate': 0.028851514307765624, 'depth': 6, 'l2_leaf_reg': 8.928427868765652, 'subsample': 0.8834315900704202, 'border_count': 51}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 17:57:49,645] Trial 27 finished with value: 0.9108836943752951 and parameters: {'learning_rate': 0.026628221432074543, 'depth': 8, 'l2_leaf_reg': 7.857214487727067, 'subsample': 0.7052233085700853, 'border_count': 89}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 18:02:49,180] Trial 28 finished with value: 0.9069659876723114 and parameters: {'learning_rate': 0.028478178509564717, 'depth': 7, 'l2_leaf_reg': 6.398338570269159, 'subsample': 0.7629589076335355, 'border_count': 77}. Best is trial 18 with value: 0.9131764436954789.
[I 2026-01-31 18:09:01,975] Trial 29 finished with value: 0.9136427641858275 and parameters: {'learning_rate': 0.02981042395461884, 'depth': 8, 'l2_leaf_reg': 2.952349471973724, 'subsample': 0.8169494246499783, 'border_count': 60}. Best is trial 29 with value: 0.9136427641858275.

[INFO] Best CatBoost params: {'learning_rate': 0.02981042395461884, 'depth': 8, 'l2_leaf_reg': 2.952349471973724, 'subsample': 0.8169494246499783, 'border_count': 60}
0:	test: 0.8371169	best: 0.8371169 (0)	total: 548ms	remaining: 45m 37s
100:	test: 0.9078392	best: 0.9078392 (100)	total: 54.8s	remaining: 44m 16s
200:	test: 0.9219357	best: 0.9219357 (200)	total: 1m 48s	remaining: 43m 7s
300:	test: 0.9292013	best: 0.9292194 (299)	total: 2m 42s	remaining: 42m 12s
400:	test: 0.9344752	best: 0.9344752 (400)	total: 3m 35s	remaining: 41m 12s
500:	test: 0.9388403	best: 0.9388403 (500)	total: 4m 28s	remaining: 40m 15s
600:	test: 0.9415051	best: 0.9417845 (597)	total: 5m 22s	remaining: 39m 17s
700:	test: 0.9434117	best: 0.9436037 (699)	total: 6m 15s	remaining: 38m 24s
800:	test: 0.9438413	best: 0.9441916 (751)	total: 7m 8s	remaining: 37m 27s
900:	test: 0.9449926	best: 0.9449945 (899)	total: 8m 2s	remaining: 36m 36s
1000:	test: 0.9452020	best: 0.9454843 (934)	total: 8m 55s	remaining: 35m 39s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.945484283
bestIteration = 934

Shrink model to first 935 iterations.

In [23]:
evaluate_and_log(model_catboost_full,  X_test, y_test, experiment_name=EXPERIMENT_NAME, run_name="CATboost_Optuna_fullfeatures", hp_search_history=hist_df, hp_search_plots= plot_paths)

[INFO] Logged metrics: {'roc_auc': np.float64(0.9133429614436699), 'pr_auc': np.float64(0.5314019713155806), 'precision': 0.27443080670851683, 'recall': 0.7207185039370079, 'f1': 0.3975028838976725, 'custom_loss': np.float64(1.0265519693839538), 'precision_at_1000': 0.865, 'recall_at_1000': 0.2128444881889764, 'precision_at_5000': 0.459, 'recall_at_5000': 0.5647145669291339, 'precision_at_10000': 0.2885, 'recall_at_10000': 0.7098917322834646, 'cost_opt_threshold': 0.15351352260533843, 'cost_opt_custom_loss': 0.6073508991770245, 'cost_opt_precision': 0.09081363547567885, 'cost_opt_recall': 0.9151082677165354, 'cost_opt_f1': 0.16523014039452638}
[INFO] Logged SHAP summary plot.

2026/01/31 18:18:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.

{'roc_auc': np.float64(0.9133429614436699),
 'pr_auc': np.float64(0.5314019713155806),
 'precision': 0.27443080670851683,
 'recall': 0.7207185039370079,
 'f1': 0.3975028838976725,
 'custom_loss': np.float64(1.0265519693839538),
 'precision_at_1000': 0.865,
 'recall_at_1000': 0.2128444881889764,
 'precision_at_5000': 0.459,
 'recall_at_5000': 0.5647145669291339,
 'precision_at_10000': 0.2885,
 'recall_at_10000': 0.7098917322834646,
 'cost_opt_threshold': 0.15351352260533843,
 'cost_opt_custom_loss': 0.6073508991770245,
 'cost_opt_precision': 0.09081363547567885,
 'cost_opt_recall': 0.9151082677165354,
 'cost_opt_f1': 0.16523014039452638}

## 2. Reduced Features

In [24]:
# ---- 1. Compute SHAP importance for each model ----
df_xgb = get_top_features_shap(model_xgboost_full, X_train, y_train).rename(
    columns={"importance": "importance_xgb"}
)
df_lgbm = get_top_features_shap(model_lgbm_full, X_train, y_train).rename(
    columns={"importance": "importance_lgbm"}
)
df_cat = get_top_features_shap(model_catboost_full, X_train, y_train).rename(
    columns={"importance": "importance_cat"}
)

# ---- 2. Merge all importance tables ----
df = (
    df_xgb.merge(df_lgbm, on="feature")
          .merge(df_cat, on="feature")
)

# ---- 3. Rank features within each model (1 = most important) ----
df["rank_xgb"] = df["importance_xgb"].rank(method="min", ascending=False)
df["rank_lgbm"] = df["importance_lgbm"].rank(method="min", ascending=False)
df["rank_cat"] = df["importance_cat"].rank(method="min", ascending=False)

# ---- 4. Determine the top 30% threshold ----
n_features = len(df)
top_30_cutoff = int(n_features * 0.30)

# ---- 5. Check if a feature appears in top 30% in each model ----
df["in_top_xgb"]  = df["rank_xgb"]  <= top_30_cutoff
df["in_top_lgbm"] = df["rank_lgbm"] <= top_30_cutoff
df["in_top_cat"]  = df["rank_cat"]  <= top_30_cutoff

# ---- 6. Apply the rule: “Top 30% for at least 2 models” ----
df["top_count"] = (
    df["in_top_xgb"].astype(int)
  + df["in_top_lgbm"].astype(int)
  + df["in_top_cat"].astype(int)
)

df_selected = df[df["top_count"] >= 2]  # final selected features

In [25]:
# ---- 7. Sort by mean importance (optional but nice) ----
df_selected["importance_mean"] = df_selected[["importance_xgb","importance_lgbm","importance_cat"]].mean(axis=1)
df_selected = df_selected.sort_values("importance_mean", ascending=False)

# ---- 8. Save to CSV ----
df.to_csv(f"{data_folder}/feature_importances_shap_fullmodels.csv", index=False)
df_selected.to_csv(f"{data_folder}/selected_features_shap.csv", index=False)

# ---- 9. List of selected feature names ----
selected_feature_list = df_selected["feature"].tolist()

In [26]:
del df_xgb, df_lgbm, df_cat, df_selected, df

In [27]:
X_train_reduced = X_train[selected_feature_list]
X_test_reduced = X_test[selected_feature_list]

In [28]:
X_train_reduced.shape, X_test_reduced.shape

((99594, 215), (118108, 215))

### 2.1. XGBoost

In [29]:
model_xgboost_reduced, best_params_xgboost_reduced, hist_df, plot_paths = train_xgb_optuna(X_train_reduced, y_train)

[I 2026-01-31 18:23:45,776] A new study created in memory with name: xgboost_aucpr_optimization

[Optuna XGBoost Tuning]:   0%|          | 0/30 [00:00<?, ?trial/s]

[I 2026-01-31 18:24:31,414] Trial 0 finished with value: 0.9040205788771352 and parameters: {'learning_rate': 0.012457011471071472, 'max_depth': 6, 'subsample': 0.5092046997823447, 'colsample_bytree': 0.5421151584253756, 'min_child_weight': 0.04821413802598553, 'gamma': 2.920239865974992}. Best is trial 0 with value: 0.9040205788771352.
[I 2026-01-31 18:25:17,652] Trial 1 finished with value: 0.9122803215125228 and parameters: {'learning_rate': 0.026375447241818978, 'max_depth': 7, 'subsample': 0.7694868928356835, 'colsample_bytree': 0.5656384717418156, 'min_child_weight': 0.04278374913512064, 'gamma': 3.377761891261342}. Best is trial 1 with value: 0.9122803215125228.
[I 2026-01-31 18:25:57,902] Trial 2 finished with value: 0.8990861145355605 and parameters: {'learning_rate': 0.019010876168376475, 'max_depth': 5, 'subsample': 0.5725898920540669, 'colsample_bytree': 0.7569241787661868, 'min_child_weight': 0.0014443867013356443, 'gamma': 4.50792951503597}. Best is trial 1 with value: 0.9122803215125228.
[I 2026-01-31 18:26:33,063] Trial 3 finished with value: 0.8781398104572388 and parameters: {'learning_rate': 0.016420483644646336, 'max_depth': 3, 'subsample': 0.6448808369071888, 'colsample_bytree': 0.834413337554907, 'min_child_weight': 0.44956720308159565, 'gamma': 3.280344255423946}. Best is trial 1 with value: 0.9122803215125228.
[I 2026-01-31 18:27:27,819] Trial 4 finished with value: 0.9036221552485487 and parameters: {'learning_rate': 0.01236457232664026, 'max_depth': 7, 'subsample': 0.6653435155260281, 'colsample_bytree': 0.8343773726366607, 'min_child_weight': 0.12893135203027603, 'gamma': 0.8253816767129235}. Best is trial 1 with value: 0.9122803215125228.
[I 2026-01-31 18:28:08,372] Trial 5 finished with value: 0.9010055714640729 and parameters: {'learning_rate': 0.019135500040247846, 'max_depth': 5, 'subsample': 0.8822679736549139, 'colsample_bytree': 0.5100299375032948, 'min_child_weight': 0.020455990608870354, 'gamma': 2.4661959317279614}. Best is trial 1 with value: 0.9122803215125228.
[I 2026-01-31 18:28:45,006] Trial 6 finished with value: 0.8947330272561715 and parameters: {'learning_rate': 0.020892672908532722, 'max_depth': 4, 'subsample': 0.96081190485812, 'colsample_bytree': 0.5102219192469843, 'min_child_weight': 0.8864479285137217, 'gamma': 3.4951424411981433}. Best is trial 1 with value: 0.9122803215125228.
[I 2026-01-31 18:29:22,485] Trial 7 finished with value: 0.8959150626192001 and parameters: {'learning_rate': 0.029269892364045688, 'max_depth': 4, 'subsample': 0.6638701229493893, 'colsample_bytree': 0.6209564044571886, 'min_child_weight': 0.014290458621967761, 'gamma': 2.765521064068715}. Best is trial 1 with value: 0.9122803215125228.
[I 2026-01-31 18:30:11,229] Trial 8 finished with value: 0.9115558486976254 and parameters: {'learning_rate': 0.027869713339807138, 'max_depth': 7, 'subsample': 0.6606138924522331, 'colsample_bytree': 0.9402667910401411, 'min_child_weight': 0.0021476325861481196, 'gamma': 1.9184442749568515}. Best is trial 1 with value: 0.9122803215125228.
[I 2026-01-31 18:31:04,917] Trial 9 finished with value: 0.9053784852081628 and parameters: {'learning_rate': 0.014629422977372108, 'max_depth': 7, 'subsample': 0.542027023804815, 'colsample_bytree': 0.997773778829488, 'min_child_weight': 0.001872539438765436, 'gamma': 2.5352363717337028}. Best is trial 1 with value: 0.9122803215125228.
[I 2026-01-31 18:32:03,075] Trial 10 finished with value: 0.9168077281016466 and parameters: {'learning_rate': 0.024575114828181695, 'max_depth': 8, 'subsample': 0.8206075747915009, 'colsample_bytree': 0.6445702310957755, 'min_child_weight': 0.005961009454565394, 'gamma': 4.78718607082145}. Best is trial 10 with value: 0.9168077281016466.
[I 2026-01-31 18:32:58,598] Trial 11 finished with value: 0.916798672885517 and parameters: {'learning_rate': 0.02470626647751087, 'max_depth': 8, 'subsample': 0.7884001644212739, 'colsample_bytree': 0.6447704061593613, 'min_child_weight': 0.006710386151412557, 'gamma': 4.985106255286258}. Best is trial 10 with value: 0.9168077281016466.
[I 2026-01-31 18:33:56,125] Trial 12 finished with value: 0.9158942321770479 and parameters: {'learning_rate': 0.024277314500600177, 'max_depth': 8, 'subsample': 0.8109841887912683, 'colsample_bytree': 0.6559620256886719, 'min_child_weight': 0.005757124286226596, 'gamma': 4.904490070799471}. Best is trial 10 with value: 0.9168077281016466.
[I 2026-01-31 18:34:53,481] Trial 13 finished with value: 0.9174280650150846 and parameters: {'learning_rate': 0.023283849941454653, 'max_depth': 8, 'subsample': 0.8549746126407124, 'colsample_bytree': 0.6907405995463753, 'min_child_weight': 0.006675692562532754, 'gamma': 4.2578878314294295}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:35:51,482] Trial 14 finished with value: 0.9158204434589092 and parameters: {'learning_rate': 0.022272748447231414, 'max_depth': 8, 'subsample': 0.874252861141543, 'colsample_bytree': 0.7194321082969803, 'min_child_weight': 0.005258471072581819, 'gamma': 4.219865629388135}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:36:37,885] Trial 15 finished with value: 0.909117097797253 and parameters: {'learning_rate': 0.02291998910567765, 'max_depth': 6, 'subsample': 0.9846803506064027, 'colsample_bytree': 0.7275581369551954, 'min_child_weight': 0.010497113695286837, 'gamma': 4.087584944448028}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:37:36,443] Trial 16 finished with value: 0.9161226376624579 and parameters: {'learning_rate': 0.02582037830793204, 'max_depth': 8, 'subsample': 0.8820013848652586, 'colsample_bytree': 0.7944742075178433, 'min_child_weight': 0.0036031910757290063, 'gamma': 3.949714445230185}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:38:21,588] Trial 17 finished with value: 0.9042051265399879 and parameters: {'learning_rate': 0.016814068546745345, 'max_depth': 6, 'subsample': 0.7282368296742185, 'colsample_bytree': 0.6846880178419482, 'min_child_weight': 0.14007927967263906, 'gamma': 1.617688333971691}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:39:17,903] Trial 18 finished with value: 0.9165535240600976 and parameters: {'learning_rate': 0.021201635477140695, 'max_depth': 8, 'subsample': 0.8366576838311607, 'colsample_bytree': 0.6000349754959139, 'min_child_weight': 0.02372455765655472, 'gamma': 4.543794751857095}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:40:10,533] Trial 19 finished with value: 0.9163425147858737 and parameters: {'learning_rate': 0.029393978785832275, 'max_depth': 7, 'subsample': 0.9265999400099226, 'colsample_bytree': 0.6839867318507152, 'min_child_weight': 0.0010520431206828568, 'gamma': 0.02260186483368276}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:41:10,316] Trial 20 finished with value: 0.9144161543934811 and parameters: {'learning_rate': 0.02332686513627398, 'max_depth': 8, 'subsample': 0.7280509128092278, 'colsample_bytree': 0.7873371560137785, 'min_child_weight': 0.002919439510572785, 'gamma': 3.692956691421398}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:42:04,505] Trial 21 finished with value: 0.9160670583308336 and parameters: {'learning_rate': 0.025206311971857354, 'max_depth': 8, 'subsample': 0.7794463942306209, 'colsample_bytree': 0.6289964642120164, 'min_child_weight': 0.008066666105772377, 'gamma': 4.892019145767142}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:42:53,075] Trial 22 finished with value: 0.9151450080277771 and parameters: {'learning_rate': 0.02710748751392347, 'max_depth': 7, 'subsample': 0.8266873581962265, 'colsample_bytree': 0.5872288130237299, 'min_child_weight': 0.004481062417612204, 'gamma': 4.9805460091977425}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:43:51,678] Trial 23 finished with value: 0.9173664508846694 and parameters: {'learning_rate': 0.024265642291446732, 'max_depth': 8, 'subsample': 0.9259394750346587, 'colsample_bytree': 0.6584492076236376, 'min_child_weight': 0.011533636588053633, 'gamma': 4.472985295985705}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:44:50,885] Trial 24 finished with value: 0.9159352138177965 and parameters: {'learning_rate': 0.021931554197041077, 'max_depth': 8, 'subsample': 0.930095475673534, 'colsample_bytree': 0.6893600127323315, 'min_child_weight': 0.012762168642969158, 'gamma': 4.44332520482023}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:45:46,408] Trial 25 finished with value: 0.9053512462633703 and parameters: {'learning_rate': 0.010082191505479742, 'max_depth': 7, 'subsample': 0.9282710288670328, 'colsample_bytree': 0.7453821581114847, 'min_child_weight': 0.028335682678480457, 'gamma': 3.8481924231682485}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:46:32,841] Trial 26 finished with value: 0.9084110300852157 and parameters: {'learning_rate': 0.019731159348776152, 'max_depth': 6, 'subsample': 0.8697577645991887, 'colsample_bytree': 0.6611080286145907, 'min_child_weight': 0.072202811231733, 'gamma': 4.355569018852128}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:47:26,161] Trial 27 finished with value: 0.917006740582777 and parameters: {'learning_rate': 0.024172259509523786, 'max_depth': 8, 'subsample': 0.9967889086272154, 'colsample_bytree': 0.5582509679608056, 'min_child_weight': 0.01644222955794572, 'gamma': 4.592249893637074}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:48:18,164] Trial 28 finished with value: 0.9125008060405736 and parameters: {'learning_rate': 0.01791703421468235, 'max_depth': 7, 'subsample': 0.9917396697978517, 'colsample_bytree': 0.5677278397999534, 'min_child_weight': 0.016524867405757857, 'gamma': 4.04644267913541}. Best is trial 13 with value: 0.9174280650150846.
[I 2026-01-31 18:49:02,814] Trial 29 finished with value: 0.9113508798417967 and parameters: {'learning_rate': 0.02716928205131823, 'max_depth': 6, 'subsample': 0.9579322325162267, 'colsample_bytree': 0.5544245928300529, 'min_child_weight': 0.05915782244585465, 'gamma': 3.631377089367831}. Best is trial 13 with value: 0.9174280650150846.

[INFO] Best XGBoost params: {'learning_rate': 0.023283849941454653, 'max_depth': 8, 'subsample': 0.8549746126407124, 'colsample_bytree': 0.6907405995463753, 'min_child_weight': 0.006675692562532754, 'gamma': 4.2578878314294295}
[0]	validation_0-auc:0.82491
[100]	validation_0-auc:0.92245
[200]	validation_0-auc:0.93369
[300]	validation_0-auc:0.93891
[400]	validation_0-auc:0.94102
[500]	validation_0-auc:0.94154
[596]	validation_0-auc:0.94112

In [30]:
evaluate_and_log(model_xgboost_reduced, X_test_reduced, y_test, experiment_name=EXPERIMENT_NAME, run_name="XGBoost_Optuna_Reduced", hp_search_history=hist_df, hp_search_plots= plot_paths)
evaluate_and_log(model_xgboost_reduced, X_test_reduced, y_test, experiment_name=EXPERIMENT_NAME, run_name="XGBoost_Optuna_Reduced", hp_search_history=hist_df, hp_search_plots= plot_paths, prediction_threshold=0.10)
evaluate_and_log(model_xgboost_reduced, X_test_reduced, y_test, experiment_name=EXPERIMENT_NAME, run_name="XGBoost_Optuna_Reduced", hp_search_history=hist_df, hp_search_plots= plot_paths, prediction_threshold=0.02)

[INFO] Logged metrics: {'roc_auc': np.float64(0.9066869277315813), 'pr_auc': np.float64(0.5073270129949601), 'precision': 0.2696087696087696, 'recall': 0.7020177165354331, 'f1': 0.38959442851290454, 'custom_loss': np.float64(1.0907728519659972), 'precision_at_1000': 0.858, 'recall_at_1000': 0.2111220472440945, 'precision_at_5000': 0.4392, 'recall_at_5000': 0.5403543307086615, 'precision_at_10000': 0.2816, 'recall_at_10000': 0.6929133858267716, 'cost_opt_threshold': 0.1528395105097162, 'cost_opt_custom_loss': 0.6091712669759881, 'cost_opt_precision': 0.09194975098491043, 'cost_opt_recall': 0.9131397637795275, 'cost_opt_f1': 0.16707561398374715}
[INFO] Logged SHAP summary plot.

2026/01/31 18:49:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.
[INFO] Logged metrics: {'roc_auc': np.float64(0.9066869277315813), 'pr_auc': np.float64(0.5073270129949601), 'precision': 0.06964613511204813, 'recall': 0.9429133858267716, 'f1': 0.12971143268172972, 'custom_loss': np.float64(0.6298387916144546), 'precision_at_1000': 0.858, 'recall_at_1000': 0.2111220472440945, 'precision_at_5000': 0.4392, 'recall_at_5000': 0.5403543307086615, 'precision_at_10000': 0.2816, 'recall_at_10000': 0.6929133858267716, 'cost_opt_threshold': 0.1528395105097162, 'cost_opt_custom_loss': 0.6091712669759881, 'cost_opt_precision': 0.09194975098491043, 'cost_opt_recall': 0.9131397637795275, 'cost_opt_f1': 0.16707561398374715}
[INFO] Logged SHAP summary plot.

2026/01/31 18:50:18 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.
[INFO] Logged metrics: {'roc_auc': np.float64(0.9066869277315813), 'pr_auc': np.float64(0.5073270129949601), 'precision': 0.037398943574332356, 'recall': 0.9982775590551181, 'f1': 0.07209688741192255, 'custom_loss': np.float64(0.8900497849425949), 'precision_at_1000': 0.858, 'recall_at_1000': 0.2111220472440945, 'precision_at_5000': 0.4392, 'recall_at_5000': 0.5403543307086615, 'precision_at_10000': 0.2816, 'recall_at_10000': 0.6929133858267716, 'cost_opt_threshold': 0.1528395105097162, 'cost_opt_custom_loss': 0.6091712669759881, 'cost_opt_precision': 0.09194975098491043, 'cost_opt_recall': 0.9131397637795275, 'cost_opt_f1': 0.16707561398374715}
[INFO] Logged SHAP summary plot.

2026/01/31 18:50:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.

{'roc_auc': np.float64(0.9066869277315813),
 'pr_auc': np.float64(0.5073270129949601),
 'precision': 0.037398943574332356,
 'recall': 0.9982775590551181,
 'f1': 0.07209688741192255,
 'custom_loss': np.float64(0.8900497849425949),
 'precision_at_1000': 0.858,
 'recall_at_1000': 0.2111220472440945,
 'precision_at_5000': 0.4392,
 'recall_at_5000': 0.5403543307086615,
 'precision_at_10000': 0.2816,
 'recall_at_10000': 0.6929133858267716,
 'cost_opt_threshold': 0.1528395105097162,
 'cost_opt_custom_loss': 0.6091712669759881,
 'cost_opt_precision': 0.09194975098491043,
 'cost_opt_recall': 0.9131397637795275,
 'cost_opt_f1': 0.16707561398374715}

### 2.2. LightGBM

In [31]:
model_lgmb_reduced, best_params_lgmb_reduced, hist_df, plot_paths = train_lgbm_optuna(X_train_reduced, y_train)

[I 2026-01-31 18:50:51,851] A new study created in memory with name: lgbm_aucpr_optimization

[Optuna LightGBM Tuning]:   0%|          | 0/30 [00:00<?, ?trial/s]

[I 2026-01-31 18:52:25,239] Trial 0 finished with value: 0.9307106338227653 and parameters: {'num_leaves': 409, 'max_depth': 20, 'learning_rate': 0.012617677365577252, 'min_child_samples': 31, 'reg_alpha': 0.00621846665787934, 'reg_lambda': 0.1905380543418821, 'colsample_bytree': 0.9080818556399682, 'subsample': 0.8679805876123267}. Best is trial 0 with value: 0.9307106338227653.
[I 2026-01-31 18:53:31,103] Trial 1 finished with value: 0.9265881102991319 and parameters: {'num_leaves': 455, 'max_depth': 13, 'learning_rate': 0.01285825425253809, 'min_child_samples': 31, 'reg_alpha': 0.18280365184336073, 'reg_lambda': 0.3508208061525542, 'colsample_bytree': 0.9360860443007635, 'subsample': 0.8800657429117448}. Best is trial 0 with value: 0.9307106338227653.
[I 2026-01-31 18:53:58,685] Trial 2 finished with value: 0.926366716083289 and parameters: {'num_leaves': 245, 'max_depth': 10, 'learning_rate': 0.028604634501820936, 'min_child_samples': 95, 'reg_alpha': 0.13487184272258318, 'reg_lambda': 0.020285772218259057, 'colsample_bytree': 0.9504696694426548, 'subsample': 0.9484145217637742}. Best is trial 0 with value: 0.9307106338227653.
[I 2026-01-31 18:54:42,566] Trial 3 finished with value: 0.9309023156821815 and parameters: {'num_leaves': 258, 'max_depth': 17, 'learning_rate': 0.021043521347097825, 'min_child_samples': 98, 'reg_alpha': 0.14831439886817843, 'reg_lambda': 0.2834688832418345, 'colsample_bytree': 0.8647526773833566, 'subsample': 0.9430942655596161}. Best is trial 3 with value: 0.9309023156821815.
[I 2026-01-31 18:55:31,775] Trial 4 finished with value: 0.9298512699880269 and parameters: {'num_leaves': 281, 'max_depth': 17, 'learning_rate': 0.022991691851136267, 'min_child_samples': 19, 'reg_alpha': 0.3877771281110485, 'reg_lambda': 0.22542543315916225, 'colsample_bytree': 0.8350407087029866, 'subsample': 0.8238128489909134}. Best is trial 3 with value: 0.9309023156821815.
[I 2026-01-31 18:56:08,717] Trial 5 finished with value: 0.9303425827239774 and parameters: {'num_leaves': 146, 'max_depth': 15, 'learning_rate': 0.027610391843054367, 'min_child_samples': 80, 'reg_alpha': 0.1035211128674135, 'reg_lambda': 0.25593575381683187, 'colsample_bytree': 0.9949990282756964, 'subsample': 0.9705950212458991}. Best is trial 3 with value: 0.9309023156821815.
[I 2026-01-31 18:56:54,193] Trial 6 finished with value: 0.9250989435599054 and parameters: {'num_leaves': 158, 'max_depth': 13, 'learning_rate': 0.012941360083039708, 'min_child_samples': 24, 'reg_alpha': 0.49844686927827764, 'reg_lambda': 0.28589984288435544, 'colsample_bytree': 0.9904731073757072, 'subsample': 0.894694846291653}. Best is trial 3 with value: 0.9309023156821815.
[I 2026-01-31 18:57:43,227] Trial 7 finished with value: 0.9315396632638122 and parameters: {'num_leaves': 154, 'max_depth': 20, 'learning_rate': 0.024660814667918626, 'min_child_samples': 24, 'reg_alpha': 0.37901210421243436, 'reg_lambda': 0.4738179658564008, 'colsample_bytree': 0.9133507761525851, 'subsample': 0.8002477403555456}. Best is trial 7 with value: 0.9315396632638122.
[I 2026-01-31 18:58:20,797] Trial 8 finished with value: 0.9323657106234814 and parameters: {'num_leaves': 505, 'max_depth': 20, 'learning_rate': 0.029445089433342203, 'min_child_samples': 95, 'reg_alpha': 0.2636259511644248, 'reg_lambda': 0.3196643441338314, 'colsample_bytree': 0.8024964869556185, 'subsample': 0.9015309210950521}. Best is trial 8 with value: 0.9323657106234814.
[I 2026-01-31 18:59:09,275] Trial 9 finished with value: 0.9312416857797271 and parameters: {'num_leaves': 373, 'max_depth': 20, 'learning_rate': 0.02262617403897116, 'min_child_samples': 41, 'reg_alpha': 0.08170899414207583, 'reg_lambda': 0.004970769311940404, 'colsample_bytree': 0.8579914930336847, 'subsample': 0.9012072813688358}. Best is trial 8 with value: 0.9323657106234814.
[I 2026-01-31 19:00:05,893] Trial 10 finished with value: 0.932458337852584 and parameters: {'num_leaves': 487, 'max_depth': 17, 'learning_rate': 0.01737700916312611, 'min_child_samples': 66, 'reg_alpha': 0.2897448326247354, 'reg_lambda': 0.43983588039451305, 'colsample_bytree': 0.815052140641658, 'subsample': 0.9912744470675209}. Best is trial 10 with value: 0.932458337852584.
[I 2026-01-31 19:01:13,789] Trial 11 finished with value: 0.9327738998913113 and parameters: {'num_leaves': 511, 'max_depth': 18, 'learning_rate': 0.01697504506371335, 'min_child_samples': 67, 'reg_alpha': 0.27307498247898504, 'reg_lambda': 0.46874615197527847, 'colsample_bytree': 0.8024721698357918, 'subsample': 0.9981551443088011}. Best is trial 11 with value: 0.9327738998913113.
[I 2026-01-31 19:02:09,299] Trial 12 finished with value: 0.9327323748047095 and parameters: {'num_leaves': 512, 'max_depth': 17, 'learning_rate': 0.016976625446416926, 'min_child_samples': 64, 'reg_alpha': 0.29273934133048585, 'reg_lambda': 0.4775616008517493, 'colsample_bytree': 0.8152652352061042, 'subsample': 0.996791557990204}. Best is trial 11 with value: 0.9327738998913113.
[I 2026-01-31 19:03:12,721] Trial 13 finished with value: 0.9322195684792209 and parameters: {'num_leaves': 423, 'max_depth': 18, 'learning_rate': 0.01719972552935316, 'min_child_samples': 57, 'reg_alpha': 0.3347585320794356, 'reg_lambda': 0.4079975483776479, 'colsample_bytree': 0.8530992883990719, 'subsample': 0.9992514259523226}. Best is trial 11 with value: 0.9327738998913113.
[I 2026-01-31 19:03:57,427] Trial 14 finished with value: 0.9315990837092508 and parameters: {'num_leaves': 359, 'max_depth': 15, 'learning_rate': 0.01719046781047123, 'min_child_samples': 72, 'reg_alpha': 0.20886738876131433, 'reg_lambda': 0.38913542425173464, 'colsample_bytree': 0.8251663966249674, 'subsample': 0.9437004100948889}. Best is trial 11 with value: 0.9327738998913113.
[I 2026-01-31 19:05:11,089] Trial 15 finished with value: 0.9321705534841517 and parameters: {'num_leaves': 508, 'max_depth': 18, 'learning_rate': 0.015186340983070878, 'min_child_samples': 55, 'reg_alpha': 0.461813488857147, 'reg_lambda': 0.484894823639979, 'colsample_bytree': 0.870680093378847, 'subsample': 0.9695508428666992}. Best is trial 11 with value: 0.9327738998913113.
[I 2026-01-31 19:06:09,793] Trial 16 finished with value: 0.9321380474291311 and parameters: {'num_leaves': 452, 'max_depth': 18, 'learning_rate': 0.019591903109336735, 'min_child_samples': 81, 'reg_alpha': 0.3212288107734765, 'reg_lambda': 0.14598836634384732, 'colsample_bytree': 0.8035859694414026, 'subsample': 0.9768312752248807}. Best is trial 11 with value: 0.9327738998913113.
[I 2026-01-31 19:07:11,552] Trial 17 finished with value: 0.9301539760111028 and parameters: {'num_leaves': 355, 'max_depth': 16, 'learning_rate': 0.014894558463432264, 'min_child_samples': 48, 'reg_alpha': 0.21597280827827803, 'reg_lambda': 0.4987289040475592, 'colsample_bytree': 0.8820773690877963, 'subsample': 0.9278639263431844}. Best is trial 11 with value: 0.9327738998913113.
[I 2026-01-31 19:08:05,595] Trial 18 finished with value: 0.9305033605400926 and parameters: {'num_leaves': 458, 'max_depth': 13, 'learning_rate': 0.010322492247316316, 'min_child_samples': 67, 'reg_alpha': 0.39269840822409907, 'reg_lambda': 0.35982550810536346, 'colsample_bytree': 0.8407975852578292, 'subsample': 0.8485496906679033}. Best is trial 11 with value: 0.9327738998913113.
[I 2026-01-31 19:08:49,221] Trial 19 finished with value: 0.9304867992830442 and parameters: {'num_leaves': 409, 'max_depth': 14, 'learning_rate': 0.02001100419081804, 'min_child_samples': 83, 'reg_alpha': 0.2565035773649716, 'reg_lambda': 0.4308288153107496, 'colsample_bytree': 0.8889788245912567, 'subsample': 0.9273941316333267}. Best is trial 11 with value: 0.9327738998913113.
[I 2026-01-31 19:09:26,100] Trial 20 finished with value: 0.9268073406475761 and parameters: {'num_leaves': 313, 'max_depth': 10, 'learning_rate': 0.015282335173164355, 'min_child_samples': 57, 'reg_alpha': 0.3207906607695701, 'reg_lambda': 0.10371199141920062, 'colsample_bytree': 0.8270973756301868, 'subsample': 0.9849140274129287}. Best is trial 11 with value: 0.9327738998913113.
[I 2026-01-31 19:10:16,986] Trial 21 finished with value: 0.9329616279101017 and parameters: {'num_leaves': 511, 'max_depth': 17, 'learning_rate': 0.01801205787408243, 'min_child_samples': 67, 'reg_alpha': 0.28283300625288077, 'reg_lambda': 0.4401700047422943, 'colsample_bytree': 0.8181415611089053, 'subsample': 0.9965761716406641}. Best is trial 21 with value: 0.9329616279101017.
[I 2026-01-31 19:11:15,236] Trial 22 finished with value: 0.9328774015612655 and parameters: {'num_leaves': 472, 'max_depth': 19, 'learning_rate': 0.01875288667519417, 'min_child_samples': 72, 'reg_alpha': 0.22395974424195003, 'reg_lambda': 0.4467322608367934, 'colsample_bytree': 0.8024406187464572, 'subsample': 0.9619366575678461}. Best is trial 21 with value: 0.9329616279101017.
[I 2026-01-31 19:12:11,310] Trial 23 finished with value: 0.93326183473811 and parameters: {'num_leaves': 476, 'max_depth': 19, 'learning_rate': 0.018914845492223862, 'min_child_samples': 77, 'reg_alpha': 0.21620311160802458, 'reg_lambda': 0.43540052684985797, 'colsample_bytree': 0.8000015738162387, 'subsample': 0.959130528217203}. Best is trial 23 with value: 0.93326183473811.
[I 2026-01-31 19:13:07,074] Trial 24 finished with value: 0.932128383323728 and parameters: {'num_leaves': 466, 'max_depth': 19, 'learning_rate': 0.019330544035225265, 'min_child_samples': 88, 'reg_alpha': 0.20924835123044822, 'reg_lambda': 0.3791705425195929, 'colsample_bytree': 0.8447949585543546, 'subsample': 0.9572823936125607}. Best is trial 23 with value: 0.93326183473811.
[I 2026-01-31 19:14:03,422] Trial 25 finished with value: 0.9319075490144497 and parameters: {'num_leaves': 434, 'max_depth': 19, 'learning_rate': 0.021712520252432345, 'min_child_samples': 73, 'reg_alpha': 0.1842287967942329, 'reg_lambda': 0.4282166884932685, 'colsample_bytree': 0.821838204141332, 'subsample': 0.9312498982502166}. Best is trial 23 with value: 0.93326183473811.
[I 2026-01-31 19:14:58,096] Trial 26 finished with value: 0.9325031090449825 and parameters: {'num_leaves': 380, 'max_depth': 19, 'learning_rate': 0.019372709503528214, 'min_child_samples': 74, 'reg_alpha': 0.07654015978131071, 'reg_lambda': 0.3270904830764686, 'colsample_bytree': 0.839234310910742, 'subsample': 0.9638041957017819}. Best is trial 23 with value: 0.93326183473811.
[I 2026-01-31 19:15:39,319] Trial 27 finished with value: 0.9315846580833881 and parameters: {'num_leaves': 475, 'max_depth': 16, 'learning_rate': 0.02483942213009297, 'min_child_samples': 86, 'reg_alpha': 0.23824525173819192, 'reg_lambda': 0.44180337528398955, 'colsample_bytree': 0.8133395282498809, 'subsample': 0.9136660690366286}. Best is trial 23 with value: 0.93326183473811.
[I 2026-01-31 19:16:32,243] Trial 28 finished with value: 0.9329037739873863 and parameters: {'num_leaves': 482, 'max_depth': 19, 'learning_rate': 0.018323516217078263, 'min_child_samples': 49, 'reg_alpha': 0.16041573943166593, 'reg_lambda': 0.3952132056815641, 'colsample_bytree': 0.800203733690404, 'subsample': 0.9794279213102107}. Best is trial 23 with value: 0.93326183473811.
[I 2026-01-31 19:17:38,154] Trial 29 finished with value: 0.9299711629740642 and parameters: {'num_leaves': 394, 'max_depth': 16, 'learning_rate': 0.014464253562361307, 'min_child_samples': 41, 'reg_alpha': 0.14864966484796197, 'reg_lambda': 0.3978996011225121, 'colsample_bytree': 0.9113684131124171, 'subsample': 0.9816343058203106}. Best is trial 23 with value: 0.93326183473811.

[INFO] Best LightGBM params: {'num_leaves': 476, 'max_depth': 19, 'learning_rate': 0.018914845492223862, 'min_child_samples': 77, 'reg_alpha': 0.21620311160802458, 'reg_lambda': 0.43540052684985797, 'colsample_bytree': 0.8000015738162387, 'subsample': 0.959130528217203}
[50]	valid_0's auc: 0.939624	valid_0's binary_logloss: 0.294966
[100]	valid_0's auc: 0.945467	valid_0's binary_logloss: 0.24908
[150]	valid_0's auc: 0.94815	valid_0's binary_logloss: 0.226742
[200]	valid_0's auc: 0.948894	valid_0's binary_logloss: 0.215514
[250]	valid_0's auc: 0.949286	valid_0's binary_logloss: 0.208146
[300]	valid_0's auc: 0.949302	valid_0's binary_logloss: 0.202745
[350]	valid_0's auc: 0.949313	valid_0's binary_logloss: 0.198585
[400]	valid_0's auc: 0.949449	valid_0's binary_logloss: 0.195473
[450]	valid_0's auc: 0.949723	valid_0's binary_logloss: 0.193293
[500]	valid_0's auc: 0.949733	valid_0's binary_logloss: 0.192264
[550]	valid_0's auc: 0.950292	valid_0's binary_logloss: 0.191378
[600]	valid_0's auc: 0.950169	valid_0's binary_logloss: 0.192165

In [32]:
evaluate_and_log(model_lgmb_reduced, X_test_reduced, y_test, experiment_name=EXPERIMENT_NAME, run_name="LGBM_Optuna_Reduced", hp_search_history=hist_df, hp_search_plots= plot_paths)
evaluate_and_log(model_lgmb_reduced, X_test_reduced, y_test, experiment_name=EXPERIMENT_NAME, run_name="LGBM_Optuna_Reduced", hp_search_history=hist_df, hp_search_plots= plot_paths, prediction_threshold=0.1)
evaluate_and_log(model_lgmb_reduced, X_test_reduced, y_test, experiment_name=EXPERIMENT_NAME, run_name="LGBM_Optuna_Reduced", hp_search_history=hist_df, hp_search_plots= plot_paths, prediction_threshold=0.02)

[INFO] Logged metrics: {'roc_auc': np.float64(0.9190690740788815), 'pr_auc': np.float64(0.5737307057157822), 'precision': 0.4026762097401587, 'recall': 0.6368110236220472, 'f1': 0.493375274044419, 'custom_loss': np.float64(1.2822078098011989), 'precision_at_1000': 0.899, 'recall_at_1000': 0.22121062992125984, 'precision_at_5000': 0.481, 'recall_at_5000': 0.5917814960629921, 'precision_at_10000': 0.2893, 'recall_at_10000': 0.7118602362204725, 'cost_opt_threshold': 0.041898332815971794, 'cost_opt_custom_loss': 0.5763538456328107, 'cost_opt_precision': 0.08939462255867486, 'cost_opt_recall': 0.9269192913385826, 'cost_opt_f1': 0.16306300456680303}
[INFO] Logged SHAP summary plot.

2026/01/31 19:19:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.
[INFO] Logged metrics: {'roc_auc': np.float64(0.9190690740788815), 'pr_auc': np.float64(0.5737307057157822), 'precision': 0.14123172855002633, 'recall': 0.8582677165354331, 'f1': 0.24255067626299504, 'custom_loss': np.float64(0.6672621668303587), 'precision_at_1000': 0.899, 'recall_at_1000': 0.22121062992125984, 'precision_at_5000': 0.481, 'recall_at_5000': 0.5917814960629921, 'precision_at_10000': 0.2893, 'recall_at_10000': 0.7118602362204725, 'cost_opt_threshold': 0.041898332815971794, 'cost_opt_custom_loss': 0.5763538456328107, 'cost_opt_precision': 0.08939462255867486, 'cost_opt_recall': 0.9269192913385826, 'cost_opt_f1': 0.16306300456680303}
[INFO] Logged SHAP summary plot.

2026/01/31 19:20:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.
[INFO] Logged metrics: {'roc_auc': np.float64(0.9190690740788815), 'pr_auc': np.float64(0.5737307057157822), 'precision': 0.06618157204501227, 'recall': 0.9623523622047244, 'f1': 0.12384616602542789, 'custom_loss': np.float64(0.5967758322890914), 'precision_at_1000': 0.899, 'recall_at_1000': 0.22121062992125984, 'precision_at_5000': 0.481, 'recall_at_5000': 0.5917814960629921, 'precision_at_10000': 0.2893, 'recall_at_10000': 0.7118602362204725, 'cost_opt_threshold': 0.041898332815971794, 'cost_opt_custom_loss': 0.5763538456328107, 'cost_opt_precision': 0.08939462255867486, 'cost_opt_recall': 0.9269192913385826, 'cost_opt_f1': 0.16306300456680303}
[INFO] Logged SHAP summary plot.

2026/01/31 19:21:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.

{'roc_auc': np.float64(0.9190690740788815),
 'pr_auc': np.float64(0.5737307057157822),
 'precision': 0.06618157204501227,
 'recall': 0.9623523622047244,
 'f1': 0.12384616602542789,
 'custom_loss': np.float64(0.5967758322890914),
 'precision_at_1000': 0.899,
 'recall_at_1000': 0.22121062992125984,
 'precision_at_5000': 0.481,
 'recall_at_5000': 0.5917814960629921,
 'precision_at_10000': 0.2893,
 'recall_at_10000': 0.7118602362204725,
 'cost_opt_threshold': 0.041898332815971794,
 'cost_opt_custom_loss': 0.5763538456328107,
 'cost_opt_precision': 0.08939462255867486,
 'cost_opt_recall': 0.9269192913385826,
 'cost_opt_f1': 0.16306300456680303}

### 2.3. CatBoost

In [33]:
model_catoost_reduced, best_params_catoost_reduced, hist_df, plot_paths = train_catboost_optuna(X_train_reduced, y_train)

[I 2026-01-31 19:21:49,064] A new study created in memory with name: catboost_aucpr_optimization

[Optuna CatBoost Tuning]:   0%|          | 0/30 [00:00<?, ?trial/s]

[I 2026-01-31 19:24:20,653] Trial 0 finished with value: 0.9023827289217031 and parameters: {'learning_rate': 0.025126514235149562, 'depth': 6, 'l2_leaf_reg': 8.989307459478326, 'subsample': 0.959783617703367, 'border_count': 107}. Best is trial 0 with value: 0.9023827289217031.
[I 2026-01-31 19:25:43,797] Trial 1 finished with value: 0.8826267540058531 and parameters: {'learning_rate': 0.024900969525766276, 'depth': 3, 'l2_leaf_reg': 2.2871097366231474, 'subsample': 0.9832492216669126, 'border_count': 79}. Best is trial 0 with value: 0.9023827289217031.
[I 2026-01-31 19:27:03,730] Trial 2 finished with value: 0.8818411563065777 and parameters: {'learning_rate': 0.025080130787834186, 'depth': 3, 'l2_leaf_reg': 8.724818211999102, 'subsample': 0.7970559142281773, 'border_count': 52}. Best is trial 0 with value: 0.9023827289217031.
[I 2026-01-31 19:29:11,502] Trial 3 finished with value: 0.90018169845954 and parameters: {'learning_rate': 0.028364794532828495, 'depth': 5, 'l2_leaf_reg': 5.536517899271129, 'subsample': 0.9949776081553331, 'border_count': 33}. Best is trial 0 with value: 0.9023827289217031.
[I 2026-01-31 19:31:38,642] Trial 4 finished with value: 0.9012522173065904 and parameters: {'learning_rate': 0.02286871675497327, 'depth': 6, 'l2_leaf_reg': 9.307394736761148, 'subsample': 0.7443897660806015, 'border_count': 91}. Best is trial 0 with value: 0.9023827289217031.
[I 2026-01-31 19:34:39,498] Trial 5 finished with value: 0.9083253113972786 and parameters: {'learning_rate': 0.02267107712256476, 'depth': 7, 'l2_leaf_reg': 2.1305630986494855, 'subsample': 0.8590097405168562, 'border_count': 94}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 19:37:09,942] Trial 6 finished with value: 0.9023914543029631 and parameters: {'learning_rate': 0.022242506720568496, 'depth': 6, 'l2_leaf_reg': 1.561223440541824, 'subsample': 0.829447822866537, 'border_count': 80}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 19:39:13,703] Trial 7 finished with value: 0.8946538679356287 and parameters: {'learning_rate': 0.02280141221244051, 'depth': 5, 'l2_leaf_reg': 2.9499196627412214, 'subsample': 0.6980154321575216, 'border_count': 125}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 19:40:55,163] Trial 8 finished with value: 0.8832193095178625 and parameters: {'learning_rate': 0.01743089088592885, 'depth': 4, 'l2_leaf_reg': 9.509806807743706, 'subsample': 0.744624249884554, 'border_count': 121}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 19:42:13,973] Trial 9 finished with value: 0.879935495472842 and parameters: {'learning_rate': 0.02306878767979637, 'depth': 3, 'l2_leaf_reg': 1.9372941470618943, 'subsample': 0.6515352510086145, 'border_count': 91}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 19:45:52,154] Trial 10 finished with value: 0.9032136180648392 and parameters: {'learning_rate': 0.012527373085439126, 'depth': 8, 'l2_leaf_reg': 4.434078779086841, 'subsample': 0.8794113405035103, 'border_count': 70}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 19:49:32,399] Trial 11 finished with value: 0.9009204192443674 and parameters: {'learning_rate': 0.01098547358474894, 'depth': 8, 'l2_leaf_reg': 4.512270321058276, 'subsample': 0.9029225558547623, 'border_count': 64}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 19:53:08,061] Trial 12 finished with value: 0.9082128577900054 and parameters: {'learning_rate': 0.016303129422914397, 'depth': 8, 'l2_leaf_reg': 4.329575808102383, 'subsample': 0.8628962303170156, 'border_count': 62}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 19:56:12,073] Trial 13 finished with value: 0.9025710894274065 and parameters: {'learning_rate': 0.016972459741774727, 'depth': 7, 'l2_leaf_reg': 7.1648771576842964, 'subsample': 0.884296173033678, 'border_count': 50}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 19:59:12,140] Trial 14 finished with value: 0.9044828439656185 and parameters: {'learning_rate': 0.018215295272747376, 'depth': 7, 'l2_leaf_reg': 3.5346072845679952, 'subsample': 0.8207591652086788, 'border_count': 100}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 20:02:14,045] Trial 15 finished with value: 0.8988884136843852 and parameters: {'learning_rate': 0.01379385108371748, 'depth': 7, 'l2_leaf_reg': 6.594120794993927, 'subsample': 0.9258046302359562, 'border_count': 56}. Best is trial 5 with value: 0.9083253113972786.
[I 2026-01-31 20:06:00,935] Trial 16 finished with value: 0.9107395148031179 and parameters: {'learning_rate': 0.01951315725358077, 'depth': 8, 'l2_leaf_reg': 3.7977411295826617, 'subsample': 0.8476656948991116, 'border_count': 109}. Best is trial 16 with value: 0.9107395148031179.
[I 2026-01-31 20:08:56,176] Trial 17 finished with value: 0.9045993629071831 and parameters: {'learning_rate': 0.019951830182494367, 'depth': 7, 'l2_leaf_reg': 1.050271552643155, 'subsample': 0.6052265436908426, 'border_count': 112}. Best is trial 16 with value: 0.9107395148031179.
[I 2026-01-31 20:12:31,383] Trial 18 finished with value: 0.9169283103274922 and parameters: {'learning_rate': 0.029815914713297142, 'depth': 8, 'l2_leaf_reg': 3.053552578289609, 'subsample': 0.7703746667725582, 'border_count': 93}. Best is trial 18 with value: 0.9169283103274922.
[I 2026-01-31 20:16:13,441] Trial 19 finished with value: 0.9171234648740508 and parameters: {'learning_rate': 0.029678350804988533, 'depth': 8, 'l2_leaf_reg': 5.635622027411202, 'subsample': 0.7693956922966465, 'border_count': 112}. Best is trial 19 with value: 0.9171234648740508.
[I 2026-01-31 20:19:59,203] Trial 20 finished with value: 0.9178686009983267 and parameters: {'learning_rate': 0.029405738753117108, 'depth': 8, 'l2_leaf_reg': 5.731959604079731, 'subsample': 0.7681630069453441, 'border_count': 117}. Best is trial 20 with value: 0.9178686009983267.
[I 2026-01-31 20:23:43,461] Trial 21 finished with value: 0.9186021037011963 and parameters: {'learning_rate': 0.029868190880973415, 'depth': 8, 'l2_leaf_reg': 5.929730438448838, 'subsample': 0.7690371333123105, 'border_count': 118}. Best is trial 21 with value: 0.9186021037011963.
[I 2026-01-31 20:27:24,752] Trial 22 finished with value: 0.9155228955178644 and parameters: {'learning_rate': 0.027801658191325018, 'depth': 8, 'l2_leaf_reg': 6.019828259930237, 'subsample': 0.7079566149713779, 'border_count': 119}. Best is trial 21 with value: 0.9186021037011963.
[I 2026-01-31 20:30:28,180] Trial 23 finished with value: 0.912082026557914 and parameters: {'learning_rate': 0.029755716835612837, 'depth': 7, 'l2_leaf_reg': 7.565792928813487, 'subsample': 0.784702838952204, 'border_count': 127}. Best is trial 21 with value: 0.9186021037011963.
[I 2026-01-31 20:34:09,733] Trial 24 finished with value: 0.9149800758876131 and parameters: {'learning_rate': 0.026812156623340036, 'depth': 8, 'l2_leaf_reg': 5.3134297812116, 'subsample': 0.7035076139605414, 'border_count': 112}. Best is trial 21 with value: 0.9186021037011963.
[I 2026-01-31 20:37:07,320] Trial 25 finished with value: 0.9103519666878711 and parameters: {'learning_rate': 0.02679573071701439, 'depth': 7, 'l2_leaf_reg': 7.647237384831905, 'subsample': 0.758564195104083, 'border_count': 102}. Best is trial 21 with value: 0.9186021037011963.
[I 2026-01-31 20:40:47,751] Trial 26 finished with value: 0.9153164006310958 and parameters: {'learning_rate': 0.02844728893932137, 'depth': 8, 'l2_leaf_reg': 5.205542183095178, 'subsample': 0.6714963847819059, 'border_count': 119}. Best is trial 21 with value: 0.9186021037011963.
[I 2026-01-31 20:43:17,188] Trial 27 finished with value: 0.9032190719552116 and parameters: {'learning_rate': 0.02660796601020674, 'depth': 6, 'l2_leaf_reg': 6.3691990597710335, 'subsample': 0.7318634040108054, 'border_count': 116}. Best is trial 21 with value: 0.9186021037011963.
[I 2026-01-31 20:45:00,619] Trial 28 finished with value: 0.8934616178859326 and parameters: {'learning_rate': 0.029978313407739095, 'depth': 4, 'l2_leaf_reg': 8.334108874868587, 'subsample': 0.8061703428568825, 'border_count': 128}. Best is trial 21 with value: 0.9186021037011963.
[I 2026-01-31 20:47:36,559] Trial 29 finished with value: 0.9026924867720512 and parameters: {'learning_rate': 0.02458312753115592, 'depth': 6, 'l2_leaf_reg': 6.851617381355171, 'subsample': 0.7761906339405124, 'border_count': 103}. Best is trial 21 with value: 0.9186021037011963.

[INFO] Best CatBoost params: {'learning_rate': 0.029868190880973415, 'depth': 8, 'l2_leaf_reg': 5.929730438448838, 'subsample': 0.7690371333123105, 'border_count': 118}
0:	test: 0.8511841	best: 0.8511841 (0)	total: 340ms	remaining: 28m 17s
100:	test: 0.9088292	best: 0.9088292 (100)	total: 33.2s	remaining: 26m 48s
200:	test: 0.9238188	best: 0.9238188 (200)	total: 1m 4s	remaining: 25m 41s
300:	test: 0.9319141	best: 0.9319141 (300)	total: 1m 35s	remaining: 24m 45s
400:	test: 0.9371184	best: 0.9371184 (400)	total: 2m 6s	remaining: 24m 5s
500:	test: 0.9414256	best: 0.9414256 (500)	total: 2m 36s	remaining: 23m 28s
600:	test: 0.9437315	best: 0.9438563 (596)	total: 3m 7s	remaining: 22m 54s
700:	test: 0.9449682	best: 0.9450022 (687)	total: 3m 38s	remaining: 22m 19s
800:	test: 0.9460613	best: 0.9463880 (772)	total: 4m 9s	remaining: 21m 46s
900:	test: 0.9468008	best: 0.9468298 (897)	total: 4m 39s	remaining: 21m 13s
1000:	test: 0.9472504	best: 0.9474193 (992)	total: 5m 10s	remaining: 20m 40s
1100:	test: 0.9473247	best: 0.9476003 (1049)	total: 5m 41s	remaining: 20m 7s
Stopped by overfitting detector  (100 iterations wait)

bestTest = 0.9476003114
bestIteration = 1049

Shrink model to first 1050 iterations.

In [34]:
evaluate_and_log(model_catoost_reduced, X_test_reduced, y_test, experiment_name=EXPERIMENT_NAME, run_name="CATBoost_Optuna_Reduced", hp_search_history=hist_df, hp_search_plots= plot_paths)
evaluate_and_log(model_catoost_reduced, X_test_reduced, y_test, experiment_name=EXPERIMENT_NAME, run_name="CATBoost_Optuna_Reduced", hp_search_history=hist_df, hp_search_plots= plot_paths, prediction_threshold=0.1)
evaluate_and_log(model_catoost_reduced, X_test_reduced, y_test, experiment_name=EXPERIMENT_NAME, run_name="CATBoost_Optuna_Reduced", hp_search_history=hist_df, hp_search_plots= plot_paths, prediction_threshold=0.02)

[INFO] Logged metrics: {'roc_auc': np.float64(0.9167651905384218), 'pr_auc': np.float64(0.5320023627515054), 'precision': 0.2749144073285833, 'recall': 0.7310531496062992, 'f1': 0.3995696321699953, 'custom_loss': np.float64(0.9917702441832899), 'precision_at_1000': 0.875, 'recall_at_1000': 0.21530511811023623, 'precision_at_5000': 0.451, 'recall_at_5000': 0.5548720472440944, 'precision_at_10000': 0.2905, 'recall_at_10000': 0.7148129921259843, 'cost_opt_threshold': 0.1292009003081632, 'cost_opt_custom_loss': 0.5906797168693061, 'cost_opt_precision': 0.08683007893643539, 'cost_opt_recall': 0.9256889763779528, 'cost_opt_f1': 0.15876767250474783}
[INFO] Logged SHAP summary plot.

2026/01/31 20:54:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.
[INFO] Logged metrics: {'roc_auc': np.float64(0.9167651905384218), 'pr_auc': np.float64(0.5320023627515054), 'precision': 0.07415413715234216, 'recall': 0.9453740157480315, 'f1': 0.13752125279642058, 'custom_loss': np.float64(0.5941087817929352), 'precision_at_1000': 0.875, 'recall_at_1000': 0.21530511811023623, 'precision_at_5000': 0.451, 'recall_at_5000': 0.5548720472440944, 'precision_at_10000': 0.2905, 'recall_at_10000': 0.7148129921259843, 'cost_opt_threshold': 0.1292009003081632, 'cost_opt_custom_loss': 0.5906797168693061, 'cost_opt_precision': 0.08683007893643539, 'cost_opt_recall': 0.9256889763779528, 'cost_opt_f1': 0.15876767250474783}
[INFO] Logged SHAP summary plot.

2026/01/31 20:54:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.
[INFO] Logged metrics: {'roc_auc': np.float64(0.9167651905384218), 'pr_auc': np.float64(0.5320023627515054), 'precision': 0.0394477894039477, 'recall': 0.9963090551181102, 'f1': 0.07589076528030289, 'custom_loss': np.float64(0.8474701121007892), 'precision_at_1000': 0.875, 'recall_at_1000': 0.21530511811023623, 'precision_at_5000': 0.451, 'recall_at_5000': 0.5548720472440944, 'precision_at_10000': 0.2905, 'recall_at_10000': 0.7148129921259843, 'cost_opt_threshold': 0.1292009003081632, 'cost_opt_custom_loss': 0.5906797168693061, 'cost_opt_precision': 0.08683007893643539, 'cost_opt_recall': 0.9256889763779528, 'cost_opt_f1': 0.15876767250474783}
[INFO] Logged SHAP summary plot.

2026/01/31 20:55:10 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

[INFO] Evaluation complete and logged.

{'roc_auc': np.float64(0.9167651905384218),
 'pr_auc': np.float64(0.5320023627515054),
 'precision': 0.0394477894039477,
 'recall': 0.9963090551181102,
 'f1': 0.07589076528030289,
 'custom_loss': np.float64(0.8474701121007892),
 'precision_at_1000': 0.875,
 'recall_at_1000': 0.21530511811023623,
 'precision_at_5000': 0.451,
 'recall_at_5000': 0.5548720472440944,
 'precision_at_10000': 0.2905,
 'recall_at_10000': 0.7148129921259843,
 'cost_opt_threshold': 0.1292009003081632,
 'cost_opt_custom_loss': 0.5906797168693061,
 'cost_opt_precision': 0.08683007893643539,
 'cost_opt_recall': 0.9256889763779528,
 'cost_opt_f1': 0.15876767250474783}

In [35]:
from pathlib import Path
importlib.reload(feature_importance)
from feature_importance import save_shap_case_studies

case_studies_dir = Path("ai-gen/results/shap_case_studies_xgb_full")
save_shap_case_studies(
    model=model_lgmb_reduced,
    X=X_test_reduced,
    y=y_test,
    out_dir=case_studies_dir
)

    case_id  row_index  true_label  pred_prob  pred_label bucket
7   case_08       7618           1   0.499205           0     FN
3   case_04      46203           1   0.498938           0     FN
18  case_19      64067           1   0.497960           0     FN
14  case_15      17313           1   0.497594           0     FN
4   case_05       4762           1   0.497460           0     FN
36  case_37      82183           1   0.001208           0     FN
12  case_13      93320           1   0.001167           0     FN
29  case_30      40476           1   0.001123           0     FN
11  case_12      54387           1   0.001073           0     FN
19  case_20       7807           1   0.001060           0     FN
15  case_16      66162           0   0.999556           1     FP
28  case_29       1277           0   0.999527           1     FP
37  case_38       1300           0   0.999522           1     FP
35  case_36       1629           0   0.999503           1     FP
9   case_10      66163           0   0.999485           1     FP
8   case_09      62577           0   0.500164           1     FP
13  case_14      62565           0   0.500164           1     FP
22  case_23      62562           0   0.500164           1     FP
23  case_24      13551           0   0.500129           1     FP
25  case_26      55652           0   0.500010           1     FP
20  case_21      66749           0   0.499958           0     TN
16  case_17      71634           0   0.499893           0     TN
39  case_40       9494           0   0.499802           0     TN
17  case_18      70791           0   0.499671           0     TN
10  case_11      55168           0   0.499521           0     TN
6   case_07      42745           0   0.000162           0     TN
27  case_28       2743           0   0.000160           0     TN
26  case_27      52003           0   0.000154           0     TN
30  case_31      45689           0   0.000148           0     TN
1   case_02       8658           0   0.000137           0     TN
33  case_34      40218           1   0.999875           1     TP
24  case_25      97419           1   0.999849           1     TP
38  case_39      35799           1   0.999849           1     TP
0   case_01      78956           1   0.999794           1     TP
31  case_32      86530           1   0.999782           1     TP
2   case_03     116262           1   0.507033           1     TP
21  case_22      24588           1   0.506473           1     TP
34  case_35     111390           1   0.504140           1     TP
5   case_06     100638           1   0.500817           1     TP
32  case_33      35734           1   0.500775           1     TP